version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Madrid"
    groups:
      typescript-eslint:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "eslint"
          - "@eslint/*"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "automated"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
