// This file is created by the Quasar CLI plugin
// It's auto-generated by @quasar/vite-plugin, do not modify manually
module.exports = {
  framework: {
    plugins: [
      'Notify',
      'Dialog',
      'Loading'
    ]
  }
}