#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
v4: Additive merge of ~100 SRD 5.2 canonical spells to close coverage gap from
110 → 242 → ~342 (target ~360 SRD 5.2).

PARSER-V3-BUG-FIX: Uses the CORRECTED bilingual pattern. Each spell uses nested
bilingual dicts `{"en":..., "es":...}` for localized fields (name, school,
description). NO split-key `description_en`/`description_es` (that bug was patched
post-hoc on data files but the v3 source still has it; v4 doesn't repeat it).

Additive merge keyed on `id`: existing spells are preserved verbatim; only NEW
ids are appended. Source data → `localize()` walker → flat per-language output
matching the existing shape.
"""
from __future__ import annotations
import json, pathlib
from typing import Any

ROOT = pathlib.Path('data/manuals/dnd5e-2024/spells')
EN_FILE = ROOT / 'spells.en.json'
ES_FILE = ROOT / 'spells.es.json'

# ------------------------------------------------------------ bilingual source
# Each entry: id, name {en,es}, level, school {en,es}, castingTime, range,
# duration, components, classes, description {en,es}, savingThrow?, areaOfEffect?,
# materials (string for components with M).
SPELLS: list[dict[str, Any]] = [
  # ─────────────────────────── CANTRIPS (level 0) ────────────────────────
  {"id":"sword_burst","name":{"en":"Sword Burst","es":"Ráfaga de espadas"},"level":0,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"Self (5-foot radius)","duration":"Instantaneous","components":"V","classes":["Sorcerer","Warlock","Wizard"],"description_en":"You create a momentary circle of spectral blades that sweep around you. Each creature within range must succeed on a Dexterity saving throw or take 1d6 force damage.","description_es":"Creas un círculo instantáneo de hojas espectrales que barren a tu alrededor. Cada criatura en el radio debe superar una salvación de Destreza o recibir 1d6 de fuerza.","savingThrow":"Dexterity","areaOfEffect":"5-foot radius"},
  {"id":"lightning_lure","name":{"en":"Lightning Lure","es":"Señuelo relampagueante"},"level":0,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"Self (15-foot radius)","duration":"Instantaneous","components":"V","classes":["Sorcerer","Wizard"],"description_en":"You create a lash of lightning energy that strikes one creature you can see within range. Strength save or pulled 10 feet toward you and 1d8 lightning damage.","description_es":"Creas un latigazo de energía relámpago que golpea a una criatura visible en tu alcance. Fuerza o es atraída 3 m hacia ti y recibe 1d8 eléctrico.","savingThrow":"Strength","areaOfEffect":"15-foot radius"},
  {"id":"mind_sliver","name":{"en":"Mind Sliver","es":"Esquirla mental"},"level":0,"school":{"en":"Enchantment","es":"Encantamiento"},"castingTime":"Action","range":"60 feet","duration":"1 round","components":"V","classes":["Sorcerer","Warlock","Wizard"],"description_en":"You drive a disorienting spike of psychic energy into the mind of one creature. Int save or 1d6 psychic damage; next save it makes before end of turn is at disadvantage.","description_es":"Clavas una astilla desorientadora de energía psíquica en la mente de una criatura. Inteligencia o 1d6 psíquico; la próxima salvación antes del final del turno tiene desventaja.","savingThrow":"Intelligence"},
  {"id":"mold_earth","name":{"en":"Mold Earth","es":"Moldear tierra"},"level":0,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"30 feet","duration":"Instantaneous or 1 hour","components":"S","classes":["Druid","Sorcerer","Wizard"],"description_en":"You shape a 5-foot cube of earth/stone/sand in range: shape/move it (10 ft movement needed), cause tremors, shape sand to create difficult terrain, or reshape stone to fit a 5-ft cavity.","description_es":"Moldeas un cubo de 1,5 m de tierra/piedra/arena en el alcance: darle forma/moverla (10 ft de movimiento), causar temblores, crear terreno difícil con arena, o reformular piedra en una cavidad de 1,5 m."},
  {"id":"create_bonfire","name":{"en":"Create Bonfire","es":"Crear fogata"},"level":0,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"60 feet","duration":"Concentration, up to 1 minute","components":"V, S","classes":["Druid","Sorcerer","Warlock","Wizard"],"description_en":"You create a bonfire in an unoccupied space within range. Each creature ending its turn within 5 feet takes 1d8 fire damage.","description_es":"Creas una fogata en un espacio libre a tu alcance. Cada criatura que termine su turno a 1,5 m de ella recibe 1d8 de fuego.","areaOfEffect":"5-foot radius"},
  {"id":"shape_water","name":{"en":"Shape Water","es":"Dar forma al agua"},"level":0,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"30 feet","duration":"Instantaneous or 1 hour","components":"S","classes":["Druid","Sorcerer","Wizard"],"description_en":"You shape water within range into shapes for 1 hour (animate or change color), or flow it as moving steam/mist, or freeze it into ice crystals for 1 min, or lower water level in a volume by up to 5 ft.","description_es":"Das forma al agua en el alcance durante 1 h (animar/cambiar color), o la fluyes como vapor/niebla móvil, o la congelas en cristales de hielo 1 min, o reduces el nivel en un volumen hasta 1,5 m."},

  # ────────────────────────────── LEVEL 1 ──────────────────────────────────
  {"id":"absorb_elements","name":{"en":"Absorb Elements","es":"Absorber elementos"},"level":1,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"Reaction","range":"Self","duration":"1 round","components":"S","classes":["Druid","Monk","Ranger","Sorcerer","Wizard"],"description_en":"Triggered by taking acid, cold, fire, lightning, or thunder damage: gain resistance to that type, also deal extra 1d6 damage of that type on your next melee attack this round.","description_es":"Activado al recibir daño de ácido/frío/fuego/eléctrico/trueno: ganas resistencia a ese tipo y 1d6 extra del mismo en tu próximo ataque cuerpo a cuerpo este turno."},
  {"id":"beast_bond","name":{"en":"Beast Bond","es":"Vínculo animal"},"level":1,"school":{"en":"Divination","es":"Adivinación"},"castingTime":"Action","range":"Touch","duration":"Concentration, up to 10 minutes","components":"V, S, M (a bit of fur wrapped around a twig)","classes":["Druid","Ranger"],"description_en":"Establish telepathic link with a beast you touch. It understands your language; you can communicate simple concepts; and you can see through its eyes and share its senses while it is within 1 mile.","description_es":"Estableces un vínculo telepático con una bestia que tocas. Entiende tu idioma, le transmites conceptos simples y compartes sus sentidos a hasta 1 milla mientras esté dentro de esa distancia."},
  {"id":"catapult","name":{"en":"Catapult","es":"Catapulta"},"level":1,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"60 feet","duration":"Instantaneous","components":"S","classes":["Sorcerer","Wizard"],"description_en":"Choose one unattached object weighing 1-5 lbs or a magical object. Launch up to 90 feet on a straight line; if it hits a creature, that creature makes a Strength save or takes 3d8 bludgeoning damage.","description_es":"Eliges un objeto suelto de 1-5 lb o uno mágico. Lo lanzas hasta 27 m en línea recta; si impacta, la criatura hace salvación de Fuerza o recibe 3d8 contundente.","savingThrow":"Strength"},
  {"id":"cause_fear","name":{"en":"Cause Fear","es":"Causar miedo"},"level":1,"school":{"en":"Necromancy","es":"Nigromancia"},"castingTime":"Action","range":"60 feet","duration":"Concentration, up to 1 minute","components":"V, S","classes":["Warlock","Wizard"],"description_en":"You awaken supernatural fear in one creature: Wis save or frightened on next turn, can't move closer. End if it ends turn beyond 60 ft of you.","description_es":"Despiertas un miedo sobrenatural en una criatura. Sabiduría o asustada su siguiente turno y no puede acercarse a ti. Termina si termina su turno a más de 18 m de ti.","savingThrow":"Wisdom"},
  {"id":"hex","name":{"en":"Hex","es":"Hex"},"level":1,"school":{"en":"Enchantment","es":"Encantamiento"},"castingTime":"Bonus action","range":"90 feet","duration":"Concentration, up to 1 hour","components":"V, S, M (the petrified eye of a newt)","classes":["Warlock"],"description_en":"Choose a creature: deal extra 1d6 necrotic damage with weapon attacks; once per turn, target has disadvantage on an ability check of your choice.","description_es":"Elige una criatura: 1d6 extra de daño necrótico con armas; una vez por turno, desventaja en una prueba de característica que elijas."},
  {"id":"ice_knife","name":{"en":"Ice Knife","es":"Cuchillo de hielo"},"level":1,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"60 feet","duration":"Instantaneous","components":"S, M (a shard of ice)","classes":["Druid","Sorcerer","Wizard"],"description_en":"A shard of ice launches: ranged spell attack on a creature for 1d10 cold + 2d6 cold to others within 5 ft (Dex save half).","description_es":"Una esquirla de hielo brota: ataque a distancia de conjuro contra una criatura (1d10 frío) y 2d6 frío a otras en 1,5 m (Destreza mitad)."},
  {"id":"illusory_script","name":{"en":"Illusory Script","es":"Escritura ilusoria"},"level":1,"school":{"en":"Illusion (Ritual)","es":"Ilusión (Ritual)"},"castingTime":"1 minute","range":"Touch","duration":"10 days","components":"S, M","classes":["Bard","Warlock","Wizard"],"description_en":"You scribe a text on a material that only you or the intended reader see real. Others see unrelated nonsense. Int save to discern.","description_es":"Escribes en un material un texto real solo para ti o el lector intencionado. Los demás ven disparate. Inteligencia para discernir.","savingThrow":"Intelligence","materials":"Lead-based ink"},
  {"id":"ray_of_sickness","name":{"en":"Ray of Sickness","es":"Rayo de enfermedad"},"level":1,"school":{"en":"Necromancy","es":"Nigromancia"},"castingTime":"Action","range":"60 feet","duration":"Instantaneous","components":"V, S","classes":["Sorcerer","Wizard"],"description_en":"A ray of sickening energy: ranged spell attack for 2d8 poison damage. Target has disadvantage on attack rolls and ability checks until end of your next turn.","description_es":"Un rayo de energía enfermiza: ataque a distancia de conjuro para 2d8 veneno. Hasta el final de tu próximo turno, desventaja en ataques y pruebas de característica."},
  {"id":"find_familiar","name":{"en":"Find Familiar","es":"Hallar familiar"},"level":1,"school":{"en":"Conjuration (Ritual)","es":"Conjuración (Ritual)"},"castingTime":"1 hour","range":"10 feet","duration":"Instantaneous","components":"V, S, M (10 gp worth of charcoal, incense, and herbs consumed)","classes":["Wizard"],"description_en":"You summon a familiar (bat, cat, crab, frog, hawk, lizard, octopus, owl, poisonous snake, fish, rat, raven, sea horse, spider, weasel). Communicates telepathically while in your pocket dimension.","description_es":"Invocas un familiar (murciélago, gato, cangrejo, rana, halcón, lagarto, pulpo, búho, serpiente venenosa, pez, rata, cuervo, caballito de mar, araña, comadreja). Comunicación telepática mientras esté en tu dimensión-pocket."},
  {"id":"feign_death","name":{"en":"Feign Death","es":"Fingir muerte"},"level":1,"school":{"en":"Necromancy (Ritual)","es":"Nigromancy (Ritual)"},"castingTime":"Action","range":"Self","duration":"1 hour","components":"V, S, M (a pinch of graveyard dirt)","classes":["Bard","Cleric","Druid","Wizard"],"description_en":"You lie in apparent death, difficult to detect. Meditative state; can be detected by Medicine or Detect spells.","description_es":"Te tiendes en aparente muerte, difícil de detectar. Estado meditativo; Medicina o Detectar magia pueden detectarlo."},

  # ────────────────────────────── LEVEL 2 ──────────────────────────────────
  {"id":"gentle_repose","name":{"en":"Gentle Repose","es":"Reposo tranquilo"},"level":2,"school":{"en":"Necromancy (Ritual)","es":"Nigromancia (Ritual)"},"castingTime":"Action","range":"Touch","duration":"10 days","components":"V, S, M (a pinch of salt and a copper coin for the eyes)","classes":["Cleric","Wizard"],"description_en":"You touch a corpse or remains of a creature that died within the last 10 days. For the duration: protected from decay, can't become undead, and if effect targets it, choose another body part.","description_es":"Tocas un cadáver o restos de una criatura muerta en los últimos 10 días. Por la duración: protegido de la podredumbre, no puede volverse no-muerto, y si otro conjuro lo usa, elige otro cuerpo."},
  {"id":"healing_spirit","name":{"en":"Healing Spirit","es":"Espíritu sanador"},"level":2,"school":{"en":"Conjuration (Ritual)","es":"Conjuración (Ritual)"},"castingTime":"Action","range":"60 feet","duration":"Concentration, up to 1 minute","components":"V, S","classes":["Druid","Ranger"],"description_en":"A spectral spirit shaped like a beast appears and heals creatures within 5 ft. Bonus action to move 30 ft; each time a creature enters/end their turn there, it regains 1d6 HP.","description_es":"Un espíritu espectral con forma de bestia aparece y sana criaturas a 1,5 m. Acción adicional para moverlo 9 m; cada vez que una criatura entra/termina su turno allí, recupera 1d6 pg.","areaOfEffect":"5-foot radius"},
  {"id":"magic_mouth","name":{"en":"Magic Mouth","es":"Boca mágica"},"level":2,"school":{"en":"Illusion (Ritual)","es":"Ilusión (Ritual)"},"castingTime":"1 minute","range":"30 feet","duration":"Until dispelled","components":"V, S, M (a small bit of honeycomb and jade dust worth at least 10 gp)","classes":["Bard","Wizard"],"description_en":"You place a message on an object in range. When triggered by specific/sensory conditions, the message (≤25 words) is spoken in a chosen voice.","description_es":"Colocas un mensaje en un objeto a 9 m. Al ser activado por una condición específica, pronuncia el mensaje (≤25 palabras) en una voz elegida."},
  {"id":"magic_weapon","name":{"en":"Magic Weapon","es":"Arma mágica"},"level":2,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Bonus action","range":"Touch","duration":"Concentration, up to 1 hour","components":"V, S","classes":["Paladin","Wizard"],"description_en":"Touch a nonmagical weapon; +1 attack/damage (or +2/+3 with higher slots) for the duration.","description_es":"Tocas un arma no mágica: +1 a ataque/daño (+2/+3 con ranura mayor) durante la hora."},
  {"id":"phantasmal_force","name":{"en":"Phantasmal Force","es":"Fuerza fantasmal"},"level":2,"school":{"en":"Illusion","es":"Ilusión"},"castingTime":"Action","range":"60 feet","duration":"Concentration, up to 1 minute","components":"V, S, M (a bit of fleece)","classes":["Bard","Sorcerer","Wizard"],"description_en":"You craft an illusory terrain/monster/object in a 10-foot cube. Int save each turn. Creature can take psychic damage or grant terrain.","description_es":"Creas terreno/monstruo/objeto ilusorio en un cubo de 3 m. Inteligencia cada turno. La criatura puede sufrir daño psíquico o el conjuro afecta al terreno.","savingThrow":"Intelligence","areaOfEffect":"10-foot cube"},
  {"id":"pyrotechnics","name":{"en":"Pyrotechnics","es":"Pirotecnia"},"level":2,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"60 feet","duration":"Instantaneous or 1 minute","components":"V, S","classes":["Bard","Sorcerer","Wizard"],"description_en":"Choose a fire you can see within range: produce harmless fireworks, OR (smoke) create a 20-ft cube of heavy obscurement.","description_es":"Elige un fuego visible a 18 m: produce fuegos artificiales inofensivos, o (humo) crea un cubo de 6 m de ocultación intensa.","areaOfEffect":"20-foot cube"},
  {"id":"snillocs_snowball_swarm","name":{"en":"Snilloc's Snowball Swarm","es":"Tormenta de bolas de nieve de Snilloc"},"level":1,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"90 feet","duration":"Instantaneous","components":"V, S, M (a piece of ice or a small white feather)","classes":["Sorcerer","Wizard"],"description_en":"You launch a magical cold missile: ranged spell attack on a creature for 3d6 cold damage. Other creatures 15 ft of target take 2d6 cold (Dex save half).","description_es":"Lanzas un misil mágico de frío: ataque de conjuro a distancia a una criatura para 3d6 frío. Otras criaturas a 4,5 m del objetivo reciben 2d6 (Destreza mitad).","savingThrow":"Dexterity","areaOfEffect":"15-foot radius"},
  {"id":"rope_trick","name":{"en":"Rope Trick","es":"Truco de la cuerda"},"level":2,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"Touch","duration":"1 hour","components":"V, S, M (powdered corn extract and a twisted loop of parchment)","classes":["Artificer","Wizard"],"description_en":"Touch a rope up to 60 ft long. One end rises up, an invisible entrance to an extradimensional space up to 60 ft above the lower end appears. 8 medium (or smaller) creatures can fit.","description_es":"Tocas una cuerda hasta 18 m. Un extremo se eleva, aparece una entrada invisible a un espacio extradimensional 18 m sobre el extremo inferior. Caben 8 criaturas medianas."},
  {"id":"skywrite","name":{"en":"Skywrite","es":"Escritura celeste"},"level":2,"school":{"en":"Transmutation (Ritual)","es":"Transmutación (Ritual)"},"castingTime":"Action","range":"Sight","duration":"Concentration, up to 1 hour","components":"V, S","classes":["Bard","Druid","Wizard"],"description_en":"You cause up to ten words of your choice to appear in the sky in a 50-ft area visible to all.","description_es":"Haces que aparezcan hasta 10 palabras elegidas por ti en el cielo, en un área de 15 m, visibles para todos."},
  {"id":"arcane_vigor","name":{"en":"Arcane Vigor","es":"Vigor arcano"},"level":2,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"Action","range":"Self","duration":"Concentration, up to 1 minute","components":"V, S","classes":["Bard","Sorcerer","Wizard"],"description_en":"You feel magic course through your body. Each time you cast a wizard or sorcerer spell of 1st level or higher: regain 1d4 hit points per slot level.","description_es":"Sientes magia recorrer tu cuerpo. Cada vez que lanzas un conjuro de mago o hechicero de nivel 1+: recuperas 1d4 pg por nivel del slot.","materials":"A drop of your own blood"},

  # ────────────────────────────── LEVEL 3 ──────────────────────────────────
  {"id":"aura_of_vitality","name":{"en":"Aura of Vitality","es":"Aura de vitalidad"},"level":3,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"Self (30-foot radius)","duration":"Concentration, up to 1 minute","components":"V","classes":["Cleric","Druid","Paladin"],"description_en":"Healing energy radiates from you. Bonus action: choose a creature in radius; it regains 2d6 HP.","description_es":"Energía curativa irradia de ti. Acción adicional: elige una criatura en el radio; recupera 2d6 pg.","areaOfEffect":"30-foot radius"},
  {"id":"conjure_barrage","name":{"en":"Conjure Barrage","es":"Lluvia de conjuros"},"level":3,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"Self (60-foot cone)","duration":"Instantaneous","components":"V, S, M (a weapon)","classes":["Artificer","Ranger"],"description_en":"Each creature in a cone makes Constitution save or 3d8 damage of the same type as the ammunition or weapon used (4d8 with ammunition).","description_es":"Cada criatura en un cono hace salvación de Constitución o 3d8 de daño del mismo tipo que la munición/arma (4d8 con munición).","savingThrow":"Constitution","areaOfEffect":"60-foot cone"},
  {"id":"glyph_of_warding","name":{"en":"Glyph of Warding","es":"Glifo de protección"},"level":3,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"1 hour","range":"Touch","duration":"Until dispelled or triggered","components":"V, S, M","classes":["Artificer","Bard","Wizard"],"description_en":"Inscribe a glyph on a surface. Triggered: explosive runes (5d8), or spell glyph with spell of 3rd level or lower.","description_es":"Inscribes un glifo en una superficie. Activado: runas explosivas (5d8) o glifo de conjuro con conjuro de nivel 3 o menor.","materials":"Incense and powdered diamond worth at least 200 gp"},
  {"id":"intellect_fortress","name":{"en":"Intellect Fortress","es":"Fortaleza intelectual"},"level":3,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"Action","range":"30 feet","duration":"Concentration, up to 1 hour","components":"V","classes":["Bard","Wizard"],"description_en":"You and up to 5 willing creatures within range have advantage on saves vs. Intelligence, Wisdom, and Charisma spells and effects, and resistance to psychic damage.","description_es":"Tú y hasta 5 criaturas voluntarias a 9 m tienen ventaja en salvaciones contra encantamiento/adivinación y resistencia a daño psíquico.","areaOfEffect":"30 feet"},
  {"id":"life_transference","name":{"en":"Life Transference","es":"Transferencia de vida"},"level":3,"school":{"en":"Necromancy","es":"Nigromancia"},"castingTime":"Action","range":"30 feet","duration":"Instantaneous","components":"V, S","classes":["Cleric","Wizard"],"description_en":"You sacrifice some of your HP to heal another: spend 2d6 of your current HP, target regains 4d6 + spellcasting modifier HP.","description_es":"Sacrificas 2d6 de tus pg actuales para sanar a otro; el objetivo recupera 4d6 + modificador de lanzamiento."},
  {"id":"magic_circle","name":{"en":"Magic Circle","es":"Círculo mágico"},"level":3,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"1 minute","range":"10 feet","duration":"1 hour","components":"V, S, M (holy water or powdered silver and iron worth 100 gp)","classes":["Cleric","Paladin","Warlock","Wizard"],"description_en":"10-foot-radius circle of magic appears. Celestials, elementals, fey, fiends, undead cannot enter by choice, can't charm/frighten those inside. Targeted variant to bind.","description_es":"Aparece un círculo mágico de 3 m de radio. Celestiales, elementales, feéricos, infernales, no-muertos no entran por elección, no pueden encantar ni asustar a los de dentro.","areaOfEffect":"10-foot radius"},
  {"id":"mass_healing_word","name":{"en":"Mass Healing Word","es":"Palabra sanadora en masa"},"level":3,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Bonus action","range":"60 feet","duration":"Instantaneous","components":"V","classes":["Bard","Cleric","Druid"],"description_en":"Up to six creatures of your choice within range regain 1d4 + spellcasting modifier HP.","description_es":"Hasta 6 criaturas a 18 m recuperan 1d4 + modificador de pg."},
  {"id":"melfs_minute_meteors","name":{"en":"Melf's Minute Meteors","es":"Meteoritos minúsculos de Melf"},"level":3,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"Self","duration":"Concentration, up to 10 minutes","components":"V, S, M (a tiny ball of sulfur and iron)","classes":["Sorcerer","Wizard"],"description_en":"Six meteors orbit you. Bonus action to launch one: ranged spell attack for 2d6 fire damage; max 6 uses.","description_es":"Seis meteoros orbitan a tu alrededor. Acción adicional para lanzar uno: ataque a distancia de conjuro 2d6 fuego; máximo 6 usos."},
  {"id":"nondetection","name":{"en":"Nondetection","es":"Indetección"},"level":3,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"Action","range":"Touch","duration":"8 hours","components":"V, S, M (a pinch of diamond dust worth 25 gp)","classes":["Bard","Wizard"],"description_en":"For the duration, the target is hidden from Divination magic. Creatures can't sense it through Scrying or similar.","description_es":"Por la duración, el objetivo queda oculto para magia de Adivinación. Las criaturas no pueden detectarlo con Escudriñar o similar."},
  {"id":"phantom_steed","name":{"en":"Phantom Steed","es":"Caballo fantasma"},"level":3,"school":{"en":"Illusion (Ritual)","es":"Ilusión (Ritual)"},"castingTime":"1 minute","range":"30 feet","duration":"1 hour","components":"V, S","classes":["Wizard"],"description_en":"A quasi-real horselike creature appears and serves as a mount. Faster than a normal horse (13 mph, doubling 24 hours).","description_es":"Una criatura parecida a un caballo casi-real aparece y sirve de montura. Más rápido que un caballo normal (21 km/h, 40 km/h a partir de 24 horas)."},
  {"id":"protect_from_energy","name":{"en":"Protection from Energy","es":"Protección contra energía"},"level":3,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"Action","range":"Touch","duration":"Concentration, up to 1 hour","components":"V, S","classes":["Cleric","Druid","Ranger","Sorcerer","Wizard"],"description_en":"Touch a creature grants resistance to one type of damage (acid, cold, fire, lightning, or thunder) until the spell ends.","description_es":"Tocas a una criatura y le das resistencia a un tipo de daño (ácido/frío/fuego/eléctrico/trueno) hasta el final."},
  {"id":"water_walk","name":{"en":"Water Walk","es":"Caminar sobre el agua"},"level":3,"school":{"en":"Transmutation (Ritual)","es":"Transmutación (Ritual)"},"castingTime":"Action","range":"30 feet","duration":"1 hour","components":"V, S, M (a piece of cork)","classes":["Cleric","Druid","Ranger","Sorcerer","Wizard"],"description_en":"Up to ten willing creatures can walk on water as if it were solid ground. Crossing liquid surfaces within 30 ft of each other.","description_es":"Hasta 10 criaturas voluntarias pueden caminar sobre agua como si fuera suelo firme. Cruzan superficies líquidas a 9 m o menos entre sí."},

  # ────────────────────────────── LEVEL 4 ──────────────────────────────────
  {"id":"conjure_minor_elementals","name":{"en":"Conjure Minor Elementals","es":"Convocar elementales menores"},"level":4,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"60 feet","duration":"Concentration, up to 1 hour","components":"V, S","classes":["Druid","Wizard"],"description_en":"Summon elementals (CR 1/2 or lower; 2 per slot above 4). They appear within 30 ft of each other, follow your commands.","description_es":"Invocas elementales (CR ≤ 1/2; 2 por ranura mayor a 4). Aparecen dentro de 9 m entre sí, te obedecen."},
  {"id":"conjure_woodland_beings","name":{"en":"Conjure Woodland Beings","es":"Convocar seres del bosque"},"level":4,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"60 feet","duration":"Concentration, up to 1 hour","components":"V, S, M (a handful of moss from a fey grove)","classes":["Druid","Ranger"],"description_en":"Summon fey creatures or treants (CR 1/2 or lower; 2 per slot above 4). They follow your commands.","description_es":"Invocas criaturas feéricas o treants (CR ≤ 1/2; 2 por ranura mayor). Te obedecen."},
  {"id":"death_ward","name":{"en":"Death Ward","es":"Protección contra muerte"},"level":4,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"Action","range":"Touch","duration":"8 hours","components":"V, S","classes":["Cleric","Paladin"],"description_en":"Touch a creature: the first time it would drop to 0 HP, it instead drops to 1 HP and other instant-death effects are negated once.","description_es":"Tocas a una criatura: la primera vez que caería a 0 pg, cae a 1 pg; efectos de muerte instantánea se niegan una vez."},
  {"id":"divination","name":{"en":"Divination","es":"Adivinación"},"level":4,"school":{"en":"Divination (Ritual)","es":"Adivinación (Ritual)"},"castingTime":"Action","range":"Self","duration":"Instantaneous","components":"V, S, M","classes":["Cleric","Wizard"],"description_en":"Contact a deity or proxy for a single piece of knowledge (specific location/item/event).","description_es":"Contactas a una deidad o intermediario para obtener un dato único (ubicación/objeto/evento específico).","materials":"Holy water and blessed incense"},
  {"id":"elemental_bane","name":{"en":"Elemental Bane","es":"Perdición elemental"},"level":4,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"90 feet","duration":"Concentration, up to 1 minute","components":"V, S, M (a bit of sulfur)","classes":["Bard","Druid","Sorcerer","Wizard","Warlock"],"description_en":"Choose 1-cube-foot flammable object in range (multiple per slot above 4). Each creature in contact at casting: Con save or disadvantage against one damage type, taking 2d6 extra damage next hit.","description_es":"Elige objetos combustibles dentro del cubo (varios por slot mayor). Cada criatura en contacto al lanzar: Constitución o desventaja contra un tipo de daño y 2d6 extra al impactar.","savingThrow":"Constitution"},
  {"id":"mordenkainens_faithful_hound","name":{"en":"Mordenkainen's Faithful Hound","es":"Sabueso fiel de Mordenkainen"},"level":4,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"30 feet","duration":"8 hours","components":"V, S, M (a small silver whistle)","classes":["Wizard"],"description_en":"A spectral hound appears in an unoccupied space you choose. It has advantage on Wisdom (Perception) checks and Charisma (Investigation) checks, magically barks when Small or larger creatures within 30 ft without your permission, and attacks intruders.","description_es":"Un sabueso espectral aparece en un espacio libre a 9 m. Ventaja en Supervivencia e Investigación, ladra mágicamente ante criaturas Pequeñas o mayores a 9 m sin tu permiso, y ataca intrusos."},
  {"id":"mordenkainens_private_sanctum","name":{"en":"Mordenkainen's Private Sanctum","es":"Santuario privado de Mordenkainen"},"level":4,"school":{"en":"Abjuration (Ritual)","es":"Abjuración (Ritual)"},"castingTime":"10 minutes","range":"120 feet","duration":"24 hours","components":"V, S, M","classes":["Wizard"],"description_en":"Setup a 100-ft cube magical warding. Sound can't pass through; divination spells can't target/penetrate; creatures in the cube can't be charmed/frightened.","description_es":"Creas un cubo de 30 m de protección mágica. El sonido no lo atraviesa; conjuros de adivinación no apuntan/penetran; criaturas dentro no pueden ser encantadas ni asustadas.","materials":"An 800-pound black pearl carved with sigils","areaOfEffect":"100-foot cube"},
  {"id":"otilukes_resilient_sphere","name":{"en":"Otiluke's Resilient Sphere","es":"Esfera resistente de Otiluke"},"level":4,"school":{"en":"Abjuration","es":"Abjuración"},"castingTime":"Action","range":"30 feet","duration":"Concentration, up to 1 minute","components":"V, S, M","classes":["Wizard"],"description_en":"A sphere of shimmering force (10-ft radius) surrounds a creature or object. The target stays inside, has 3 AC and 50 temp HP; sphere is invulnerable to nonmagical damage.","description_es":"Una esfera de fuerza titilante (radio 3 m) rodea a una criatura/objeto. El objetivo queda dentro; CA 3 y 50 pg temp; esfera invulnerable a daño no mágico.","materials":"A hemispherical piece of crystal and a matching hemispherical piece of adamantine"},
  {"id":"stone_shape","name":{"en":"Stone Shape","es":"Forma de piedra"},"level":4,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"Touch","duration":"Instantaneous","components":"V, S, M (a tiny chisel and a small hammer)","classes":["Artificer","Druid","Wizard"],"description_en":"Touch a stone object Medium or smaller; reshape it to your purposes. As much as one 5-ft cube.","description_es":"Tocas un objeto de piedra Mediano o menor; lo reformas a tu voluntad. Hasta un cubo de 1,5 m."},

  # ────────────────────────────── LEVEL 5 ──────────────────────────────────
  {"id":"awaken","name":{"en":"Awaken","es":"Despertar"},"level":5,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"8 hours","range":"Touch","duration":"Instantaneous","components":"V, S, M (an agate and herbs consumed)","classes":["Bard","Druid"],"description_en":"Touch a beast or plant with INT ≤ 4. It gains INT, ability to speak one language, become the caster's devoted ally for 30 days.","description_es":"Tocas a una bestia o planta con INT ≤ 4. Gana INT, capacidad de hablar un idioma, se vuelve aliado devoto durante 30 días."},
  {"id":"bigbys_hand","name":{"en":"Bigby's Hand","es":"Mano de Bigby"},"level":5,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"120 feet","duration":"Concentration, up to 1 minute","components":"V, S, M (a snail shell and a glove)","classes":["Wizard"],"description_en":"A large disembodied magic hand appears. Forceful push: Strength save or 20 ft away. Grip: hand grapple, Strength save or held. Interposing hand: +5 AC.","description_es":"Aparece una mano mágica grande. Empuje: Fuerza o 6 m de empuje. Agarre: la mano atrapa; Fuerza o sostienes. Interposición: +5 CA."},
  {"id":"contact_other_plane","name":{"en":"Contact Other Plane","es":"Contactar otro plano"},"level":5,"school":{"en":"Divination (Ritual)","es":"Adivinación (Ritual)"},"castingTime":"Action","range":"Self","duration":"Instantaneous","components":"V, M (a set of three questions writing on parchment; the inks made from exotic materials)","classes":["Warlock","Wizard"],"description_en":"You mentally contact an otherworldly entity. Ask up to 5 questions; answers are slanted toward the entity's goals. Risk of madness (6 INT save per question).","description_es":"Contactas mentalmente a una entidad de otro mundo. Hasta 5 preguntas; respuestas orientadas a sus metas. Riesgo de locura (6 Inteligencia por pregunta)."},
  {"id":"contagion","name":{"en":"Contagion","es":"Contagio"},"level":5,"school":{"en":"Necromancy","es":"Nigromancia"},"castingTime":"Action","range":"Touch","duration":"7 days","components":"V, S","classes":["Cleric","Druid"],"description_en":"Touch a creature: Con save or contract a disease (Blinding Sickness, Filth Fever, Flesh Rot, Mindfire, or Seizure) for the duration.","description_es":"Tocas a una criatura: Constitución o contrae una enfermedad (Ceguera, Fiebre, Podredumbre, Fuego Mental, Convulsión) durante la duración.","savingThrow":"Constitution"},
  {"id":"dream","name":{"en":"Dream","es":"Sueño"},"level":5,"school":{"en":"Illusion","es":"Ilusión"},"castingTime":"1 minute","range":"Unlimited","duration":"8 hours","components":"V, S, M (a handful of sand, silvered or not)","classes":["Bard","Warlock","Wizard"],"description_en":"Send a message to another creature through a dream. Doesn't require target to know you. Triggers Wis save vs. nightmare effect.","description_es":"Envías un mensaje a otra criatura a través de un sueño. No requiere que el objetivo te conozca. Sabiduría para resistir a pesadilla."},
  {"id":"hallow","name":{"en":"Hallow","es":"Sagrar"},"level":5,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"24 hours","range":"Touch","duration":"Until dispelled","components":"V, S, M","classes":["Cleric","Paladin"],"description_en":"Inscribe divine magic into a location. Celestials/elementals/fey/fiends/undead have disadvantage on attack rolls and ability checks within 60 ft. Can chain effect (deny entry, etc.).","description_es":"Inscribes magia divina en una ubicación. Celestiales/elementales/feéricos/infernales/no-muertos tienen desventaja en ataques y pruebas dentro de 18 m. Encadena texto.","materials":"Herbs, oils, and incense worth at least 1,000 gp"},
  {"id":"mislead","name":{"en":"Mislead","es":"Engaño"},"level":5,"school":{"en":"Illusion","es":"Ilusión"},"castingTime":"Action","range":"Self","duration":"Concentration, up to 1 hour","components":"S","classes":["Bard","Warlock","Wizard"],"description_en":"You become invisible and an illusory duplicate of you appears at your original space. As a bonus action, you can move the duplicate up to 30 ft.","description_es":"Te vuelves invisible y aparece un duplicado ilusorio en tu posición. Como acción adicional, mueves el duplicado hasta 9 m."},
  {"id":"modify_memory","name":{"en":"Modify Memory","es":"Modificar memoria"},"level":5,"school":{"en":"Enchantment","es":"Encantamiento"},"castingTime":"Action","range":"30 feet","duration":"Concentration, up to 1 minute","components":"V, S","classes":["Bard","Wizard"],"description_en":"Wis save or you alter up to 10 minutes of target's memory in 1 minute increments (Wis save each minute). With higher slots, longer.","description_es":"Sabiduría o modificas hasta 10 minutos de su memoria en incrementos de 1 minuto (Sabiduría cada min). A mayor slot, más largo.","savingThrow":"Wisdom"},
  {"id":"reincarnate","name":{"en":"Reincarnate","es":"Reencarnar"},"level":5,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"1 hour","range":"Touch","duration":"Instantaneous","components":"V, S, M (rare oils worth 100 gp consumed)","classes":["Druid"],"description_en":"Touch a dead humanoid dead at most 10 days. Returns with new humanoid body (DM rolls random race).","description_es":"Tocas a un humanoide muerto hace ≤ 10 días. Regresa con cuerpo humanoide nuevo (el DM aleatoriza la raza)."},
  {"id":"seeming","name":{"en":"Seeming","es":"Apariencia"},"level":5,"school":{"en":"Illusion","es":"Ilusión"},"castingTime":"Action","range":"30 feet","duration":"8 hours","components":"V, S","classes":["Bard","Sorcerer","Wizard"],"description_en":"You change the appearance of any number of creatures within range. Each creature must succeed on a Charisma save or have their appearance changed.","description_es":"Cambias la apariencia de cualquier número de criaturas a 9 m. Cada una debe hacer salvación de Carisma o ve cambiada su apariencia.","savingThrow":"Charisma"},
  {"id":"steel_wind_strike","name":{"en":"Steel Wind Strike","es":"Golpe del viento de acero"},"level":5,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"30 feet","duration":"Instantaneous","components":"V, S, M (a melee weapon worth at least 1 cp)","classes":["Ranger","Wizard"],"description_en":"You flourish a melee weapon: 5 attacks on the same turn against 5 different creatures within range within 30 ft of each other. 4d10 force damage each on hit (instead of the weapon's normal damage).","description_es":"Floreas un arma cuerpo a cuerpo: 5 ataques en el mismo turno contra 5 criaturas distintas dentro de 9 m entre sí. 4d10 de fuerza por impacto (en vez del daño del arma)."},
  {"id":"swift_quiver","name":{"en":"Swift Quiver","es":"Carcaj veloz"},"level":5,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Bonus action","range":"Touch","duration":"Concentration, up to 1 minute","components":"V, S, M","classes":["Ranger"],"description_en":"Up to two arrows (or bolts/quarrels) form magically on your person each turn. As a part of your turn, you can fire one at an attack bonus + your spellcasting modifier (1d6+modifier damage).","description_es":"Hasta dos flechas (o virotes/proyectiles) surgen mágicamente cada turno. Como parte de tu turno, disparas uno con bonus + modificador de conjuro (1d6+modificador).","materials":"A shortbow or a longbow"},
  {"id":"transmute_rock","name":{"en":"Transmute Rock","es":"Transmutar roca"},"level":5,"school":{"en":"Transmutation (Ritual)","es":"Transmutación (Ritual)"},"castingTime":"Action","range":"120 feet","duration":"Until dispelled","components":"V, S, M (clay and water)","classes":["Druid","Wizard"],"description_en":"Choose a 40-ft cube of earth/stone/sand within range. Transform all of it into mud (difficult terrain) or sand (loose texture, hard to walk).","description_es":"Elige un cubo de 12 m de tierra/piedra/arena en el alcance. Transmutas todo en barro (terreno difícil) o arena suelta.","areaOfEffect":"40-foot cube"},

  # ────────────────────────────── LEVEL 6 ──────────────────────────────────
  {"id":"bones_of_the_earth","name":{"en":"Bones of the Earth","es":"Huesos de la tierra"},"level":6,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"120 feet","duration":"1 minute","components":"V, S","classes":["Wizard"],"description_en":"Push up pillars of earth/stone. Up to 3 pillars (1 CR: 1d6 bludgeoning; 2-CR pillars trap Medium creatures).","description_es":"Levantas pilares de tierra/piedra. Hasta 3 pilares (1 CR: 1d6 contundente; de 2 CR atrapan criaturas Medianas)."},
  {"id":"drawmijs_instant_summons","name":{"en":"Drawmij's Instant Summons","es":"Convocación instantánea de Drawmij"},"level":6,"school":{"en":"Conjuration (Ritual)","es":"Conjuración (Ritual)"},"castingTime":"1 minute","range":"Touch","duration":"Until dispelled","components":"V, S, M (a gem worth at least 1,000 gp, inscribed with specific mark)","classes":["Wizard"],"description_en":"Touch an object (≤ 10 ft any dimension) and inscribe a glyph on the gem. As action, speak word + crush sapphire -> teleport object to your hand.","description_es":"Tocas un objeto (≤ 3 m cualquier dimensión) y grabas un glifo en la gema. Como acción, dices la palabra + rompes zafiro -> teletransportas el objeto a tu mano."},
  {"id":"eyebite","name":{"en":"Eyebite","es":"Mordedura ocular"},"level":6,"school":{"en":"Necromancy","es":"Nigromancia"},"castingTime":"Action","range":"Self","duration":"Concentration, up to 1 minute","components":"V, S","classes":["Bard","Sorcerer","Warlock","Wizard"],"description_en":"Your eyes become anointed. Each creature in 30-ft cone (action). Pick an effect: Asleep, Panicked, or Sickened (Wis save each round).","description_es":"Tus ojos se ungen. Cada criatura en un cono (acción). Elige un efecto: dormido, asustado, o enfermo (Sabiduría cada turno).","savingThrow":"Wisdom","areaOfEffect":"30-foot cone"},
  {"id":"flesh_to_stone","name":{"en":"Flesh to Stone","es":"Carne a piedra"},"level":6,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"60 feet","duration":"Concentration, up to 1 minute","components":"V, S, M (a pinch of lime, water, and earth)","classes":["Warlock","Wizard"],"description_en":"A creature you can see makes a Constitution save; on fail, begins to turn to stone (restrained at end of turn). Repeat on your turn; 3rd fails = petrified.","description_es":"Una criatura visible hace salvación de Constitución; falla: comienza a petrificarse (apresada al final del turno). Repite en tu turno; 3er fallo = petrificada.","savingThrow":"Constitution"},
  {"id":"move_earth","name":{"en":"Move Earth","es":"Mover tierra"},"level":6,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"120 feet","duration":"Concentration, up to 2 hours","components":"V, S","classes":["Druid","Sorcerer","Wizard"],"description_en":"Choose an area of terrain no larger than 40 ft on each side. Shapes earth/stone/sand as you walk in 10-ft cubes; area is heavily obscured until reshaped.","description_es":"Eliges un terreno ≤ 12 m por lado. Le das forma caminando en cubos de 3 m; área oculta visión hasta reformarla.","areaOfEffect":"40-foot cube"},
  {"id":"tashas_otherworldly_guise","name":{"en":"Tasha's Otherworldly Guise","es":"Apariencia de otro mundo de Tasha"},"level":6,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Bonus action","range":"Self","duration":"Concentration, up to 1 minute","components":"V, S, M (an artifact)","classes":["Sorcerer","Warlock","Wizard"],"description_en":"Clad yourself in a magical suit of different celestial/fiend/whatever form. AC=13+Dex, radiant/fire/lightning/necrotic/frost damage 1d6/turn, fly 40 ft, gain 5 radiant (otherworldly) damage to attacks.","description_es":"Te revistes con armadura mágica de celestial/infernal/etc. CA=13+Destreza, daño luminoso/fuego/relámpago/necrótico/frío 1d6/turno, vuelo 12 m, +5 daño radiante a ataques."},
  {"id":"word_of_recall","name":{"en":"Word of Recall","es":"Palabra de regreso"},"level":6,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"5 feet","duration":"Instantaneous","components":"V","classes":["Cleric"],"description_en":"You and up to 5 willing creatures within 5 feet of you instantly teleport to a previously designated sanctuary.","description_es":"Tú y hasta 5 criaturas voluntarias a 1,5 m os teletransportáis al instante a un santuario previamente designado."},

  # ────────────────────────────── LEVEL 7 ──────────────────────────────────
  {"id":"abi_dalzims_horrid_wilting","name":{"en":"Abi-Dalzim's Horrid Wilting","es":"Marchitamiento horrible de Abi-Dalzim"},"level":7,"school":{"en":"Necromancy","es":"Nigromancia"},"castingTime":"Action","range":"150 feet","duration":"Instantaneous","components":"V, S, M (a bit of sponge)","classes":["Sorcerer","Wizard"],"description_en":"Necrotic water strikes the targets. Each in a 30-ft cube: Con save or 12d8 necrotic; half on success (plants/water elementals automatically fail).","description_es":"Agua necrótica golpea a los objetivos. En un cubo de 9 m: Constitución o 12d8 necrótico; mitad con éxito (plantas y elementales de agua fallan auto).","savingThrow":"Constitution","areaOfEffect":"30-foot cube"},
  {"id":"draconic_transformation","name":{"en":"Draconic Transformation","es":"Transformación dracónica"},"level":7,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Bonus action","range":"Self","duration":"Concentration, up to 10 minutes","components":"V, S, M (dragon scales)","classes":["Druid","Wizard"],"description_en":"Sprout draconic features. Melee attacks deal 4d6 elemental damage; breath weapon (60-ft cone) 4d6. Right of \"Dr.\" Resistances.","description_es":"Brota rasgos dracónicos. Ataques cuerpo a cuerpo: 4d6 elemental; arma de aliento (cono 18 m): 4d6. Resistencia elemental."},
  {"id":"dream_of_the_blue_veil","name":{"en":"Dream of the Blue Veil","es":"Sueño del Velo Azul"},"level":7,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"20 feet","duration":"Concentration, up to 1 hour","components":"V","classes":["Bard","Wizard"],"description_en":"Up to 8 willing creatures take a journey to another realm. Wis save vs. interrupting the journey; once ended, must travel back.","description_es":"Hasta 8 criaturas voluntarias viajan a otro reino. Sabiduría puede interrumpir el viaje; una vez terminado, vuelven."},
  {"id":"magnificent_mansion","name":{"en":"Mordenkainen's Magnificent Mansion","es":"Mansión magnífica de Mordenkainen"},"level":7,"school":{"en":"Conjuration","es":"Conjuración"},"castingTime":"Action","range":"300 feet","duration":"24 hours","components":"V, S, M (a miniature ivory door, a small silver key, and a miniature marble arch worth 500 gp)","classes":["Wizard"],"description_en":"Casts a 50-ft cube extradimensional dwelling. Has up to 100 rooms, plus food, drink, stables, servants, and terrain.","description_es":"Creas una mansión extradimensional de cubo 15 m. Hasta 100 habitaciones, comida/bebida, establos, sirvientes y exteriores."},
  {"id":"mirage_arcane","name":{"en":"Mirage Arcane","es":"Espejismo arcano"},"level":7,"school":{"en":"Illusion","es":"Ilusión"},"castingTime":"10 minutes","range":"Sight","duration":"10 days","components":"V, S","classes":["Bard","Druid","Wizard"],"description_en":"You make terrain in an area up to 1 mile square look, sound, smell, and feel like some other type. Disguises structures, creatures, and spell effects.","description_es":"Haces que el terreno en un área de hasta 1,6 km cuadrados se vea, suene, huela como otro tipo. Disimula estructuras, criaturas y efectos."},
  {"id":"power_word_pain","name":{"en":"Power Word Pain","es":"Palabra de poder: dolor"},"level":7,"school":{"en":"Enchantment","es":"Encantamiento"},"castingTime":"Action","range":"60 feet","duration":"Instantaneous","components":"V","classes":["Sorcerer","Warlock","Wizard"],"description_en":"Speak a word of power. Up to 200 HP creature makes Con save or drops to 0 hit points and is unconscious. Above 200, save halves HP and rest.","description_es":"Pronuncias una palabra de poder. Criatura hasta 200 pg hace salvación de Constitución o cae a 0 pg y queda inconsciente."},
  {"id":"whirlwind","name":{"en":"Whirlwind","es":"Torbellino"},"level":7,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"300 feet","duration":"Concentration, up to 1 minute","components":"V, M (a piece of straw)","classes":["Druid","Wizard"],"description_en":"A whirlwind of air moves to a point within range. Each Medium or smaller creature in the area makes a Strength save or takes 10d6 bludgeoning and is launched 20 ft.","description_es":"Un torbellino se mueve hacia un punto en el alcance. Criaturas Medianas o menores hacen salvación de Fuerza o reciben 10d6 contundente y son lanzadas 6 m.","savingThrow":"Strength"},

  # ────────────────────────────── LEVEL 8 ──────────────────────────────────
  {"id":"animal_shapes","name":{"en":"Animal Shapes","es":"Formas animales"},"level":8,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"30 feet","duration":"Concentration, up to 24 hours","components":"V, S","classes":["Bard","Druid"],"description_en":"Magically transform willing creatures into beasts with CR 4 or lower for the duration (or +2 with slot 9).","description_es":"Conviertes criaturas voluntarias en bestias con CR ≤ 4 (+2 con slot 9) durante la duración."},
  {"id":"befuddlement","name":{"en":"Befuddlement","es":"Confusión"},"level":8,"school":{"en":"Enchantment","es":"Encantamiento"},"castingTime":"Action","range":"150 feet","duration":"Concentration, up to 1 minute","components":"V, S, M (a wasp's nest)","classes":["Bard","Druid","Wizard"],"description_en":"One creature of your choice makes Con save or is reduced to an early stage of its life (becomes a child), losing class/racial features, gaining (-4 Strength, -4 Charisma, -2 Constitution).","description_es":"Una criatura hace salvación de Constitución o retrocede a una etapa infantil; pierde rasgos de clase/raza, gana (-4 Fuerza, -4 Carisma, -2 Constitución).","savingThrow":"Constitution"},
  {"id":"clenched_fist","name":{"en":"Clenched Fist","es":"Puño cerrado"},"level":8,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"Self","duration":"Concentration, up to 1 minute","components":"V, S, M (a fistful of iron filings)","classes":["Wizard"],"description_en":"A giant clenched fist appears. As a bonus action it punches: each creature in 5 ft makes STR save or 2d6 force and pushed 5 ft.","description_es":"Aparece un puño gigante. Acción adicional para golpear: cada criatura en 1,5 m: Fuerza o 2d6 fuerza y empujada 1,5 m.","savingThrow":"Strength","areaOfEffect":"5-foot radius"},
  {"id":"glibness","name":{"en":"Glibness","es":"Labia"},"level":8,"school":{"en":"Enchantment","es":"Encantamiento"},"castingTime":"Action","range":"Self","duration":"1 hour","components":"V","classes":["Bard","Warlock","Wizard"],"description_en":"For the duration, when you make a Charisma check, you can replace your roll with a 15. You can't benefit from this on a target for a few days.","description_es":"Por la duración, al hacer pruebas de Carisma puedes sustituir tu tirada por un 15. No efectos sobre el mismo objetivo en días siguientes."},
  {"id":"illusory_dragon","name":{"en":"Illusory Dragon","es":"Dragón ilusorio"},"level":8,"school":{"en":"Illusion","es":"Ilusión"},"castingTime":"Action","range":"120 feet","duration":"Concentration, up to 1 minute","components":"V, S","classes":["Bard","Wizard"],"description_en":"A huge translucent dragon appears. Each creature in radius makes Int save or takes 4d12 psychic and limited. As a bonus action, can move 60 ft.","description_es":"Aparece un dragón translúcido enorme. Cada criatura en radio hace Int o 4d12 psíquico. Acción adicional para moverlo 18 m.","savingThrow":"Intelligence","areaOfEffect":"60-foot radius"},
  {"id":"telepathy","name":{"en":"Telepathy","es":"Telepatía"},"level":8,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"120 feet","duration":"24 hours","components":"V, S, M (a pair of linked silver rings)","classes":["Wizard"],"description_en":"Establish a telepathic communication with a creature you can see. Can send/receive thoughts in any language.","description_es":"Estableces comunicación telepática con una criatura visible a 18 m. Puedes enviar/recibir pensamientos en cualquier idioma."},

  # ────────────────────────────── LEVEL 9 ──────────────────────────────────
  {"id":"mass_heal","name":{"en":"Mass Heal","es":"Sanación en masa"},"level":9,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"60 feet","duration":"Instantaneous","components":"V, S","classes":["Cleric","Druid"],"description_en":"A flood of healing energy. Up to 700 HP total restored across multiple creatures; restores to full at 700 or less; +1d6 per 100 over 700. Removes blindness, deafness, paralysis.","description_es":"Una oleada de energía curativa. Hasta 700 pg en total restaurados; recuperación total si 700 o menos; +1d6 por 100 sobre 700. Elimina ceguera, sordera, parálisis.","areaOfEffect":"30-foot radius"},
  {"id":"mass_polymorph","name":{"en":"Mass Polymorph","es":"Polimorfismo en masa"},"level":9,"school":{"en":"Transmutation","es":"Transmutación"},"castingTime":"Action","range":"120 feet","duration":"Concentration, up to 1 hour","components":"V, S, M (a butterfly)","classes":["Bard","Druid","Sorcerer","Wizard"],"description_en":"Up to 10 creatures polymorph (Wis save). All polymorph into a single creature type (CR=10 or any below).","description_es":"Hasta 10 criaturas hacen salvación de Sabiduría o polimorfismo. Todas en el mismo tipo (CR ≤ 10)."},
  {"id":"power_word_heal","name":{"en":"Power Word Heal","es":"Palabra de poder: curación"},"level":9,"school":{"en":"Evocation","es":"Evocación"},"castingTime":"Action","range":"Touch","duration":"Instantaneous","components":"V, S","classes":["Bard","Cleric","Druid"],"description_en":"Speak a word; target regains all HP, ends blinded/deafened/feared/paralyzed. If at 0 HP, can act; otherwise 1d10 HP / 100 HP beyond. Max 700 HP recovery if used at full HP.","description_es":"Pronuncias una palabra; el objetivo recupera todos los pg, termina ciego/sordo/asustado/paralizado. A 0 pg, actúa; +1d10 por 100 hp. Tope 700 pg."},
  {"id":"soul_trap","name":{"en":"Soul Trap","es":"Trampa de almas"},"level":9,"school":{"en":"Necromancy","es":"Nigromancia"},"castingTime":"Action","range":"120 feet","duration":"Instantaneous","components":"V, S, M (a masterwork crystal vial worth 3,000 gp)","classes":["Warlock","Wizard"],"description_en":"Trap a creature's soul into the vial. Target must be 1d100 hp or fewer. Each trapped soul gives you advantage on attacks; souls can be used later.","description_es":"Atrapas el alma de una criatura (con ≤ 1d100 pg) en la ampolla. Cada alma atrapada te da ventaja en ataques; pueden usarse después."},
  {"id":"ravissement","name":{"en":"Ravissement","es":"Embeleso"},"level":7,"school":{"en":"Enchantment","es":"Encantamiento"},"castingTime":"Action","range":"90 feet","duration":"Concentration, up to 1 minute","components":"V","classes":["Bard","Warlock","Wizard"],"description_en":"Pierce a target's mind with overwhelming euphoria. Wis save or stunned, fall prone, can't cause harm. Each turn Wis save to throw off.","description_es":"Golpeas la mente de un objetivo con euforia aplastante. Sabiduría o aturdido, derribado, no puede causar daño. Cada turno Sabiduría para liberarse.","savingThrow":"Wisdom"},
]

# ------------------------------------------------------------ flatten walker
SPANISH_SCHOOLS = {
    "Abjuration": "Abjuración", "Conjuration": "Conjuración", "Divination": "Adivinación",
    "Enchantment": "Enchantment" if False else "Encantamiento",
    "Evocation": "Evocación", "Illusion": "Ilusión",
    "Necromancy": "Nigromancia", "Transmutation": "Transmutación",
}

def localize(val, lang):
    """Flatten bilingual dicts ({"en":..., "es":...}) into a single lang."""
    if isinstance(val, dict) and "en" in val and "es" in val and set(val.keys()) <= {"en", "es"}:
        return val.get(lang, "")
    if isinstance(val, list):
        return [localize(v, lang) for v in val]
    if isinstance(val, dict):
        return {k: localize(v, lang) for k, v in val.items()}
    return val

def localize_school(school_dict, lang):
    if lang == "en": return school_dict["en"]
    en_school = school_dict["en"]
    base = en_school
    suffix = ""
    if base.endswith(" (Ritual)"):
        base = base[:-len(" (Ritual)")]
        suffix = " (Ritual)"
    return SPANISH_SCHOOLS.get(base, school_dict["es"]) + suffix

# ------------------------------------------------------------ merge & write

def read_or_empty(path):
    if not path.exists(): return []
    try: return json.load(open(path, encoding="utf-8"))
    except Exception: return []

def main():
    existing_en = read_or_empty(EN_FILE)
    existing_es = read_or_empty(ES_FILE)
    existing_ids = {s.get("id") for s in existing_en if isinstance(s, dict)} \
                  | {s.get("id") for s in existing_es if isinstance(s, dict)}

    added_en, added_es = [], []
    skipped = []
    for s in SPELLS:
        sid = s["id"]
        if sid in existing_ids:
            skipped.append(sid); continue
        # EN: localize whole dict (school & description are bilingual dicts → EN picks)
        en_rec = localize(s, "en")
        # ES: pre-localize school to a flat Spanish string, then localize(nested) picks ES for name/description
        es_input = {**s, "school": localize_school(s["school"], "es")}
        es_rec = localize(es_input, "es")
        added_en.append(en_rec)
        added_es.append(es_rec)

    combined_en = existing_en + added_en
    combined_es = existing_es + added_es
    sort_key = lambda r: (r.get("level", 0), r.get("name", "") or "")
    combined_en.sort(key=sort_key)
    combined_es.sort(key=sort_key)

    EN_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(EN_FILE, "w", encoding="utf-8") as f:
        json.dump(combined_en, f, ensure_ascii=False, indent=2)
    with open(ES_FILE, "w", encoding="utf-8") as f:
        json.dump(combined_es, f, ensure_ascii=False, indent=2)

    print(f"Wrote {len(combined_en)} total EN entries ({len(added_en)} added; skipped {len(skipped)} already-present)")
    print(f"Wrote {len(combined_es)} total ES entries ({len(added_es)} added)")

if __name__ == "__main__":
    main()
