"""Generate 6 additional SRD 5.2 (2024) monsters (Beholder, Mind Flayer,
Lizardfolk, Minotaur, Manticore, Wyvern) in canonical strict MonsterDetail flat
shape. Only writes NEW slugs — does NOT overwrite the 25 monsters already
generated by `generate_dnd5e_2024_monsters.py`.

Tuple schema is identical to the v1 generator; see comments there for details.
Run from `MasterHelp/backend/`.
"""

import json
import pathlib

OUT = pathlib.Path("data/manuals/dnd5e-2024/monsters")
EN = OUT / "en"
ES = OUT / "es"
EN.mkdir(parents=True, exist_ok=True)
ES.mkdir(parents=True, exist_ok=True)


# ---------- 26. Beholder ----------
M_BEHOLDER = (
    "beholder", "Beholder", "Huge",
    "aberration", "aberración",
    "lawful evil", "legal malvado",
    18, "natural armor", "armadura natural",
    180, "19d10 + 76",
    0, 20, 0, 0, 0,
    10, 14, 18, 13, 15, 17,
    "Perception +7", "Percepción +7",
    "darkvision 120 ft., passive Perception 17",
    "visión en la oscuridad 36 m, Percepción pasiva 17",
    "Deep Speech, Undercommon", "Habla profunda, Subcomún",
    "13", 10000,
    [("Antimagic Cone", "Cono antimagia",
      "The beholder's central eye creates an area of antimagic, as in the antimagic field spell, in a 150-foot cone. At the start of each of its turns, the beholder decides which way the cone faces and whether the cone is active. The central eye is immune to spells.",
      "El ojo central del observador crea un área antimagia, como en el conjuro campo antimagia, en un cono de 45 m. Al inicio de cada turno, el observador decide la dirección y si el cono está activo. Su ojo central es inmune a conjuros."),
     ("Legendary Resistance (3/Day)", "Resistencia legendaria (3/día)",
      "If the beholder fails a saving throw, it can choose to succeed instead.",
      "Si el observador falla una salvación, puede elegir tener éxito en su lugar.")],
    [("Bite", "Mordisco",
      "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 14 (4d6) piercing damage.",
      "Ataque de arma cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, un objetivo. Impacto: 14 (4d6) perforante."),
     ("Eye Rays", "Rayos oculares",
      "The beholder shoots three of the following magical eye rays at random (roll a d8 for each, no ray more than once per turn): 1-Along: charm ray, DC 16 WIS; 2-Beam: paralysis ray, DC 16 CON; 3-Down: enervation ray, 36 (8d8) necrotic; 4-Fire: 3d10 fire on each target in 20-ft line (DEX); 5-Horn: 3d8 thunder cone (CON); 6-North: ice, DEX, 4d6 cold; 7-Death: 45 (10d8) necrotic, DEX; 8-South: slowing; 9-West: telekinetic, CON.",
      "El observador dispara tres rayos oculares mágicos aleatorios (tira 1d8 por cada uno, sin repetir el mismo rayo en el mismo turno): hechizo/necrosis/llamas/hielo/muerte/parálisis/etc. (ver SRD para tabla completa; cada rayo DC 16 o 3d8/3d10 daño según descrito)."),
     ("Enslave", "Esclavizar",
      "The beholder targets one creature it can see within 30 feet of it. The target must succeed on a DC 16 Wisdom saving throw or be magically charmed by the beholder for 1 minute (concentration).",
      "El observador elige una criatura visible a 9 m. Debe superar salvación de Sabiduría CD 16 o queda hechizada (concentración 1 min).")]
)

# ---------- 27. Mind Flayer (Illithid) ----------
M_MIND_FLAYER = (
    "mind-flayer", "Mind Flayer", "Medium",
    "aberration", "aberración",
    "lawful evil", "legal malvado",
    15, "breastplate", "coraza",
    71, "13d8 + 26",
    30, 0, 0, 0, 0,
    11, 12, 17, 19, 12, 17,
    "Arcana +7, Deception +5, Insight +6, Perception +6, Persuasion +5, Stealth +4",
    "Arcanismo +7, Engaño +5, Perspicacia +6, Percepción +6, Persuasión +5, Sigilo +4",
    "blindsight 120 ft., darkvision 120 ft., passive Perception 16",
    "vista ciega 36 m, visión en la oscuridad 36 m, Percepción pasiva 16",
    "Deep Speech, Undercommon, telepathy 120 ft.",
    "Habla profunda, Subcomún, telepatía 36 m",
    "7", 2900,
    [("Magic Resistance", "Resistencia mágica",
      "The mind flayer has advantage on saving throws against spells and other magical effects.",
      "El flagelo mental tiene ventaja en salvaciones contra conjuros y efectos mágicos."),
     ("Psionics", "Psíquica",
      "The mind flayer has a swimming speed of 20 feet, can hover, and speaks Telepathy 120 ft. (described under Languages).",
      "El flagelo mental habla vía telepatía 36 m además de sus idiomas.")],
    [("Tentacles", "Tentáculos",
      "Melee Weapon Attack: +7 to hit, reach 10 ft., one creature. Hit: 15 (2d10 + 4) psychic damage. The target must succeed on a DC 15 Intelligence saving throw or have its Intelligence score reduced by 1 (to a minimum of 1). Whenever the target's Intelligence is reduced to 0 by this damage, the target is stunned and immediately aware of its surroundings.",
      "Ataque de arma cuerpo a cuerpo: +7 al impacto, alcance 3 m, una criatura. Impacto: 15 (2d10 + 4) psíquico. La víctima debe superar Inteligencia CD 15 o reduce su INT en 1 (mínimo 1). Si INT llega a 0 por este daño: queda aturdida y consciente de lo que le rodea."),
     ("Extract Brain", "Extraer cerebro",
      "The mind flayer kills one creature stunned by its tentacles by extracting and devouring its brain. The target must have an Intelligence of 5 or higher, and the mind flayer must be adjacent to it.",
      "El flagelo mata a una criatura aturdida por sus tentáculos extrayendo y devorando su cerebro. La víctima debe tener INT 5 o más y estar adyacente.")]
)

# ---------- 28. Lizardfolk ----------
M_LIZARDFOLK = (
    "lizardfolk", "Lizardfolk", "Medium",
    "humanoid (lizardfolk)", "humanoide (lagarto)",
    "neutral", "neutral",
    15, "hide armor, shield", "armadura de cuero, escudo",
    22, "4d8 + 4",
    30, 0, 0, 30, 0,
    15, 10, 13, 7, 12, 7,
    "Perception +3, Stealth +4, Survival +3",
    "Percepción +3, Sigilo +4, Supervivencia +3",
    "passive Perception 13",
    "Percepción pasiva 13",
    "Draconic", "Dracónico",
    "1/2", 100,
    [("Hold Breath", "Contener respiración",
      "The lizardfolk can hold its breath for 15 minutes.",
      "El lagarto puede contener la respiración 15 minutos.")],
    [("Multiattack", "Ataque múltiple",
      "The lizardfolk makes two attacks: one with its bite and one with its claws.",
      "El lagarto hace dos ataques: uno con su mordisco y otro con sus garras."),
     ("Bite", "Mordisco",
      "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
      "Ataque de arma cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) perforante."),
     ("Claws", "Garras",
      "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) slashing damage.",
      "Ataque de arma cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d4 + 2) cortante."),
     ("Heavy Club", "Garrote pesado",
      "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) bludgeoning damage.",
      "Ataque de arma cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 6 (1d8 + 2) contundente.")]
)

# ---------- 29. Minotaur (beast) ----------
M_MINOTAUR = (
    "minotaur", "Minotaur", "Large",
    "monstrosity", "monstruosidad",
    "chaotic evil", "caótico malvado",
    14, "natural armor", "armadura natural",
    85, "10d10 + 30",
    40, 0, 0, 0, 0,
    17, 11, 16, 6, 16, 9,
    "Perception +6", "Percepción +6",
    "darkvision 60 ft., passive Perception 16",
    "visión en la oscuridad 18 m, Percepción pasiva 16",
    "Abyssal", "Abisal",
    "3", 700,
    [("Charge", "Carga",
      "If the minotaur moves at least 30 feet straight toward a target and then hits it with a gore attack on the same turn, the target takes an extra 9 (2d8) piercing damage. If the target is a creature, it must succeed on a DC 14 Strength saving throw or be pushed up to 10 feet away and knocked prone.",
      "Si el minotauro se mueve al menos 9 m en línea recta hacia un objetivo y luego lo golpea con cornada en el mismo turno, recibe 9 (2d8) perforante extra. Si es una criatura, debe superar Fuerza CD 14 o se cae y se la empuja 3 m."),
     ("Labyrinthine Recall", "Memoria laberíntica",
      "The minotaur can perfectly recall any path it has traveled.",
      "El minotauro recuerda perfectamente cualquier camino recorrido."),
     ("Reckless", "Temerario",
      "At the start of each turn, the minotaur can gain advantage on all melee weapon attack rolls during that turn, but attack rolls against it have advantage until the start of its next turn.",
      "Al inicio de cada turno, puede ganar ventaja en todas las tiradas de ataque cuerpo a cuerpo ese turno, pero las tiradas contra él tienen ventaja hasta su próximo turno.")],
    [("Greataxe", "Hacha de dos manos",
      "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 15 (2d12 + 3) slashing damage.",
      "Ataque de arma cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 15 (2d12 + 3) cortante."),
     ("Gore", "Cornada",
      "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d8 + 3) piercing damage.",
      "Ataque de arma cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 10 (2d8 + 3) perforante.")]
)

# ---------- 30. Manticore ----------
M_MANTICORE = (
    "manticore", "Manticore", "Large",
    "monstrosity", "monstruosidad",
    "lawful evil", "legal malvado",
    14, "natural armor", "armadura natural",
    68, "8d10 + 24",
    50, 50, 0, 0, 0,
    17, 11, 15, 7, 12, 8,
    "", "",
    "darkvision 60 ft., passive Perception 11",
    "visión en la oscuridad 18 m, Percepción pasiva 11",
    "Common", "Común",
    "3", 700,
    [],
    [("Multiattack", "Ataque múltiple",
      "The manticore makes three attacks: one with its bite and two with its claws, or two tail spike attacks.",
      "La manticora hace tres ataques: uno con mordisco y dos con garras, o dos ataques con su aguijón."),
     ("Bite", "Mordisco",
      "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage.",
      "Ataque de arma cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 7 (1d8 + 3) perforante."),
     ("Claws", "Garras",
      "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.",
      "Ataque de arma cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 6 (1d6 + 3) cortante."),
     ("Tail Spike", "Aguijón de cola",
      "Ranged Weapon Attack: +6 to hit, range 150/600 ft., one target. Hit: 7 (1d8 + 3) piercing damage.",
      "Ataque de arma a distancia: +6 al impacto, alcance 45/180 m, un objetivo. Impacto: 7 (1d8 + 3) perforante.")]
)

# ---------- 31. Wyvern ----------
M_WYVERN = (
    "wyvern", "Wyvern", "Large",
    "dragon", "dragón",
    "unaligned", "sin alineamiento",
    13, "natural armor", "armadura natural",
    110, "13d10 + 39",
    20, 80, 0, 0, 0,
    19, 10, 16, 5, 12, 6,
    "", "",
    "darkvision 60 ft., passive Perception 11",
    "visión en la oscuridad 18 m, Percepción pasiva 11",
    "", "",
    "6", 2300,
    [],
    [("Multiattack", "Ataque múltiple",
      "The wyvern makes two attacks: one with its bite and one with its stinger.",
      "El wyvern hace dos ataques: uno con su mordisco y otro con su aguijón."),
     ("Bite", "Mordisco",
      "Melee Weapon Attack: +7 to hit, reach 10 ft., one creature. Hit: 11 (2d6 + 4) piercing damage.",
      "Ataque de arma cuerpo a cuerpo: +7 al impacto, alcance 3 m, una criatura. Impacto: 11 (2d6 + 4) perforante."),
     ("Stinger", "Aguijón",
      "Melee Weapon Attack: +7 to hit, reach 10 ft., one creature. Hit: 11 (2d6 + 4) piercing damage. The target must make a DC 15 Constitution saving throw, taking 24 (7d6) poison damage on a failed save, or half as much on a successful one. On a failed save, the target is also poisoned for 24 hours and can repeat the save every 24 hours, ending the effect on a success.",
      "Ataque de arma cuerpo a cuerpo: +7 al impacto, alcance 3 m, una criatura. Impacto: 11 (2d6 + 4) perforante. Constitución CD 15 o 24 (7d6) veneno (mitad éxito). En fallo, envenenado 24 h, salv cada 24 h para terminar.")]
)


ALL_NEW = [M_BEHOLDER, M_MIND_FLAYER, M_LIZARDFOLK, M_MINOTAUR, M_MANTICORE, M_WYVERN]


def split_tuple(row):
    """Tuple unpacker; aliases match generate_dnd5e_2024_monsters.py v1."""
    (slug, name, size,
     type_en, type_es,
     align_en, align_es,
     ac_val, ac_desc_en, ac_desc_es,
     hp_avg, hp_dice,
     spd_walk, spd_fly, spd_climb, spd_swim, spd_burrow,
     s_, d_, co, i_, w_, ch,
     sk_en, sk_es,
     sens_en, sens_es,
     lang_en, lang_es,
     cr, xp,
     traits, actions) = row
    return dict(
        slug=slug, name=name, size=size,
        type_en=type_en, type_es=type_es,
        align_en=align_en, align_es=align_es,
        ac_val=ac_val, ac_desc_en=ac_desc_en, ac_desc_es=ac_desc_es,
        hp_avg=hp_avg, hp_dice=hp_dice,
        spd_walk=spd_walk, spd_fly=spd_fly, spd_climb=spd_climb, spd_swim=spd_swim, spd_burrow=spd_burrow,
        str_=s_, dex_=d_, con_=co, int_=i_, wis_=w_, cha_=ch,
        sk_en=sk_en, sk_es=sk_es,
        sens_en=sens_en, sens_es=sens_es,
        lang_en=lang_en, lang_es=lang_es,
        cr=cr, xp=xp,
        traits=traits, actions=actions,
    )


def write_one(d, lang_idx):
    name = d["name"]
    type_ = [d["type_en"], d["type_es"]][lang_idx]
    align = [d["align_en"], d["align_es"]][lang_idx]
    ac_desc = [d["ac_desc_en"], d["ac_desc_es"]][lang_idx] or None
    sk_list = [s.strip() for s in ([d["sk_en"], d["sk_es"]][lang_idx]).split(",") if s.strip()]
    senses = [d["sens_en"], d["sens_es"]][lang_idx]
    langs = [d["lang_en"], d["lang_es"]][lang_idx]
    is_en = (lang_idx == 0)

    speed = {}
    if d["spd_walk"] is not None: speed["walk"] = d["spd_walk"]
    if d["spd_fly"] is not None: speed["fly"] = d["spd_fly"]
    if d["spd_climb"] is not None: speed["climb"] = d["spd_climb"]
    if d["spd_swim"] is not None: speed["swim"] = d["spd_swim"]
    if d["spd_burrow"] is not None: speed["burrow"] = d["spd_burrow"]

    abilities = {"str": d["str_"], "dex": d["dex_"], "con": d["con_"], "int": d["int_"], "wis": d["wis_"], "cha": d["cha_"]}

    return {
        "id": d["slug"],
        "slug": d["slug"],
        "lang": ["en", "es"][lang_idx],
        "source": "SRD 5.2 (2024)",
        "name": name,
        "size": d["size"],
        "type": type_,
        "alignment": align,
        "armorClass": {"value": d["ac_val"], "type": ac_desc} if ac_desc else {"value": d["ac_val"]},
        "hitPoints": {"average": d["hp_avg"], "roll": d["hp_dice"]},
        "speed": speed,
        "abilities": abilities,
        "savingThrows": [],
        "skills": sk_list,
        "damageVulnerabilities": [],
        "damageResistances": [],
        "damageImmunities": [],
        "conditionImmunities": [],
        "senses": senses,
        "languages": langs,
        "challengeRating": d["cr"],
        "experiencePoints": d["xp"],
        "traits": [{"name": t[0 if is_en else 1], "text": t[2 if is_en else 3]} for t in d["traits"]],
        "actions": [{"name": a[0 if is_en else 1], "text": a[2 if is_en else 3]} for a in d["actions"]],
    }


def main():
    written = []
    for raw in ALL_NEW:
        d = split_tuple(raw)
        for idx, lang in enumerate(["en", "es"]):
            target_dir = EN if lang == "en" else ES
            target = target_dir / f"{d['slug']}.json"
            doc = write_one(d, idx)
            target.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            written.append(str(target))
    print(f"Wrote {len(written)} new monster files ({len(ALL_NEW)} × EN+ES).")
    for w in written: print(f"  + {w}")


if __name__ == "__main__":
    main()
