#!/usr/bin/env python3
"""Add 30 more iconic SRD 5.2 (2024) monsters — EN + ES.

Dict-of-properties pattern (same as v3). Each monster is a single dict with
bilingual fields stored as {"en": ..., "es": ...} sub-dicts.

Schema invariants respected:
  - speed: {walk?, fly?, swim?, climb?, burrow?} — NO `hover` key.
  - savingThrows: object Partial<Record<AbilityKey, number>>, NOT array.
  - proficiencyBonus: CR 1-4 → 2, CR 5-8 → 3, CR 9-12 → 4.
"""
import json, pathlib

ROOT = pathlib.Path("data/manuals/dnd5e-2024/monsters")
for lang in ("en", "es"):
    (ROOT / lang).mkdir(parents=True, exist_ok=True)


def localize(val, lang):
    if isinstance(val, dict) and "en" in val and "es" in val and set(val.keys()) <= {"en", "es"}:
        return val[lang]
    if isinstance(val, list):
        return [localize(v, lang) for v in val]
    if isinstance(val, dict):
        return {k: localize(v, lang) for k, v in val.items()}
    return val


def prof_bonus(cr):
    cr = cr or ""
    if cr in {"1/8", "1/4", "1/2", "1", "2", "3", "4"}:
        return 2
    if cr in {"5", "6", "7", "8"}:
        return 3
    if cr in {"9", "10", "11", "12"}:
        return 4
    return 5


def build_canonical(m, lang):
    return {
        "id": m["slug"].replace("-", "_"),
        "slug": m["slug"],
        "lang": lang,
        "source": "SRD 5.2",
        "name": localize(m["name"], lang),
        "size": m["size"],
        "type": localize(m["type"], lang),
        "alignment": localize(m["alignment"], lang),
        "armorClass": m["armorClass"],
        "hitPoints": m["hitPoints"],
        "speed": m["speed"],
        "abilities": m["abilities"],
        "savingThrows": m.get("savingThrows"),
        "skills": m.get("skills"),
        "damageVulnerabilities": m.get("damageVulnerabilities", []),
        "damageResistances": m.get("damageResistances", []),
        "damageImmunities": m.get("damageImmunities", []),
        "conditionImmunities": m.get("conditionImmunities", []),
        "senses": localize(m["senses"], lang),
        "languages": localize(m["languages"], lang),
        "proficiencyBonus": prof_bonus(m.get("challengeRating")),
        "challengeRating": m.get("challengeRating"),
        "experiencePoints": m.get("experiencePoints"),
        "traits": localize(m.get("traits", []), lang),
        "actions": localize(m.get("actions", []), lang),
        "reactions": localize(m.get("reactions", []), lang),
        "legendaryActions": localize(m.get("legendaryActions", []), lang),
        "spellcasting": localize(m.get("spellcasting", []), lang),
        "environment": localize(m.get("environment", []), lang),
        "notes": localize(m.get("notes", []), lang),
    }


MONSTERS = [
    # === Elementals (complete the set with Earth + Water) ===
    {
        "slug": "earth-elemental",
        "name": {"en": "Earth Elemental", "es": "Elemental de tierra"},
        "type": {"en": "Elemental", "es": "Elemental"},
        "size": "Large", "alignment": {"en": "Neutral", "es": "Neutral"},
        "armorClass": {"value": 17, "type": "natural armor"},
        "hitPoints": {"average": 126, "roll": "12d10+60"},
        "speed": {"walk": 30, "burrow": 30},
        "abilities": {"str": 20, "dex": 8, "con": 20, "int": 5, "wis": 10, "cha": 5},
        "damageResistances": ["thunder"],
        "conditionImmunities": ["exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"],
        "senses": {"en": "darkvision 60 ft., tremorsense 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, sentido de vibración 18 m, Percepción pasiva 10"},
        "languages": {"en": "Terran", "es": "Terran"},
        "challengeRating": "5", "experiencePoints": 1800,
        "traits": [{"name": {"en": "Earth Glide.", "es": "Deslizamiento terrestre."},
                    "text": {"en": "The elemental can burrow through nonmagical, unworked earth and stone. While doing so, it doesn't disturb the material it moves through.",
                             "es": "El elemental puede excavar a través de tierra y piedra no-mágicas, sin trabajar. Mientras lo hace, no perturba el material a través del cual se mueve."}}],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The elemental makes two slam attacks.",
                      "es": "El elemental hace dos ataques de golpe."}},
            {"name": {"en": "Slam.", "es": "Golpe."},
             "text": {"en": "Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 14 (2d8 + 5) bludgeoning damage, or 7 (1d8 + 3) if the elemental has half HP or fewer.",
                      "es": "Ataque cuerpo a cuerpo: +8 al impacto, alcance 3 m, un objetivo. Impacto: 14 (2d8 + 5) de daño contundente, o 7 (1d8 + 3) si el elemental tiene la mitad o menos de PG."}},
        ],
    },
    {
        "slug": "water-elemental",
        "name": {"en": "Water Elemental", "es": "Elemental de agua"},
        "type": {"en": "Elemental", "es": "Elemental"},
        "size": "Large", "alignment": {"en": "Neutral", "es": "Neutral"},
        "armorClass": {"value": 14},
        "hitPoints": {"average": 114, "roll": "12d10+48"},
        "speed": {"walk": 30, "swim": 90},
        "abilities": {"str": 18, "dex": 14, "con": 18, "int": 5, "wis": 10, "cha": 8},
        "damageResistances": ["acid"],
        "conditionImmunities": ["exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"],
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "Aquan", "es": "Aquan"},
        "challengeRating": "5", "experiencePoints": 1800,
        "traits": [{"name": {"en": "Water Form.", "es": "Forma acuática."},
                    "text": {"en": "The elemental can enter a creature's space and stop there. It can move through a space as narrow as 1 inch wide without squeezing.",
                             "es": "El elemental puede entrar en el espacio de una criatura y detenerse allí. Puede moverse a través de un espacio de tan solo 2,5 cm sin apretarse."}},],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The elemental makes two slam attacks.",
                      "es": "El elemental hace dos ataques de golpe."}},
            {"name": {"en": "Slam.", "es": "Golpe."},
             "text": {"en": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) bludgeoning damage, or 7 (1d8 + 3) if the elemental has half HP or fewer.",
                      "es": "Ataque cuerpo a cuerpo: +7 al impacto, alcance 1,5 m, un objetivo. Impacto: 14 (2d8 + 5) de daño contundente, o 7 (1d8 + 3) si el elemental tiene la mitad o menos de PG."}},
            {"name": {"en": "Whelm (Recharges 4-6).", "es": "Embestida (Recarga 4-6)."},
             "text": {"en": "Each creature in the elemental's space must make a DC 15 STR save or take 14 (4d6) bludgeoning damage and be grappled (escape DC 14 STR check). The elemental can grapple one Large or smaller creature this way at a time.",
                      "es": "Cada criatura en el espacio del elemental debe superar CD 15 FUE o recibir 14 (4d6) de daño contundente y quedar apresada (escape CD 14 FUE). El elemental puede apresar así a una criatura Grande o menor cada vez."}},
        ],
    },
    # === Underdark / Aquatic humanoids ===
    {
        "slug": "drow",
        "name": {"en": "Drow", "es": "Drow"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Neutral Evil", "es": "Neutral malvado"},
        "armorClass": {"value": 15, "type": "leather armor"},
        "hitPoints": {"average": 13, "roll": "3d8"},
        "speed": {"walk": 30},
        "abilities": {"str": 10, "dex": 14, "con": 10, "int": 11, "wis": 11, "cha": 12},
        "savingThrows": {"dex": 4},
        "skills": {"perception": 2, "stealth": 4},
        "senses": {"en": "darkvision 120 ft., passive Perception 12", "es": "visión en la oscuridad 36 m, Percepción pasiva 12"},
        "languages": {"en": "Elvish, Undercommon", "es": "Élfico, infracomún"},
        "challengeRating": "1/4", "experiencePoints": 50,
        "traits": [
            {"name": {"en": "Fey Ancestry.", "es": "Ascendencia fey."},
             "text": {"en": "The drow has advantage on saving throws against being charmed, and magic can't put it to sleep.",
                      "es": "El drow tiene ventaja en salvaciones contra ser hechizado, y la magia no puede dormirlo."}},
            {"name": {"en": "Innate Spellcasting.", "es": "Lanzamiento de conjuros innato."},
             "text": {"en": "The drow's innate spellcasting ability is Charisma. It can innately cast faerie fire (at will) and darkness (1/day).", "es": "La característica de lanzamiento innato del drow es Carisma. Puede lanzar de forma innata fuego feérico (a voluntad) y oscuridad (1/día)."}},
            {"name": {"en": "Sunlight Sensitivity.", "es": "Sensibilidad a la luz solar."},
             "text": {"en": "While in sunlight, the drow has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.",
                      "es": "Bajo luz solar, el drow tiene desventaja en tiradas de ataque y en pruebas de Sabiduría (Percepción) que dependan de la vista."}},
        ],
        "actions": [
            {"name": {"en": "Shortsword.", "es": "Espada corta."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante."}},
            {"name": {"en": "Hand Crossbow.", "es": "Ballesta de mano."},
             "text": {"en": "Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 5 (1d6 + 2) piercing damage, and the target must succeed on a DC 13 CON save or be poisoned for 1 hour.",
                      "es": "Ataque a distancia: +4 al impacto, alcance 9/36 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante, y CD 13 CON o envenenado 1 hora."}},
        ],
    },
    {
        "slug": "duergar",
        "name": {"en": "Duergar", "es": "Duergar"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Lawful Evil", "es": "Legal malvado"},
        "armorClass": {"value": 16, "type": "scale mail, shield"},
        "hitPoints": {"average": 26, "roll": "4d8+8"},
        "speed": {"walk": 25},
        "abilities": {"str": 14, "dex": 11, "con": 14, "int": 11, "wis": 12, "cha": 9},
        "savingThrows": {"con": 4},
        "senses": {"en": "darkvision 120 ft., passive Perception 11", "es": "visión en la oscuridad 36 m, Percepción pasiva 11"},
        "languages": {"en": "Dwarvish, Undercommon", "es": "Enánico, infracomún"},
        "challengeRating": "1", "experiencePoints": 200,
        "traits": [
            {"name": {"en": "Duergar Resilience.", "es": "Resiliencia duergar."},
             "text": {"en": "The duergar has advantage on saving throws against poison, spells, and illusions, and has resistance against poison damage.",
                      "es": "El duergar tiene ventaja en salvaciones contra veneno, conjuros e ilusiones, y tiene resistencia al daño de veneno."}},
            {"name": {"en": "Innate Spellcasting.", "es": "Lanzamiento de conjuros innato."},
             "text": {"en": "The duergar's innate spellcasting ability is Intelligence. It can innately cast fog cloud, jump, and enlarge/reduce (each 1/day).",
                      "es": "La característica de lanzamiento innato del duergar es Inteligencia. Puede lanzar de forma innata nube de niebla, salto, y agrandar/reducir (cada uno 1/día)."},},
        ],
        "actions": [
            {"name": {"en": "War Pick.", "es": "Pico de guerra."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) piercing damage, or 11 (2d8 + 2) if used with two hands to make a melee attack.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 6 (1d8 + 2) de daño perforante, o 11 (2d8 + 2) si se usa a dos manos."}},
            {"name": {"en": "Javelin.", "es": "Javelina."},
             "text": {"en": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft. Hit: 5 (1d6 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo o distancia: +4 al impacto, alcance 1,5 m o 9/36 m. Impacto: 5 (1d6 + 2) de daño perforante."}},
        ],
    },
    {
        "slug": "merfolk",
        "name": {"en": "Merfolk", "es": "Tritón"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any alignment", "es": "Cualquier alineamiento"},
        "armorClass": {"value": 11},
        "hitPoints": {"average": 11, "roll": "2d8+2"},
        "speed": {"walk": 10, "swim": 40},
        "abilities": {"str": 10, "dex": 13, "con": 12, "int": 11, "wis": 11, "cha": 12},
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Aquan, Common", "es": "Acuano, común"},
        "challengeRating": "1/8", "experiencePoints": 25,
        "traits": [],
        "actions": [
            {"name": {"en": "Spear.", "es": "Lanza."},
             "text": {"en": "Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6 + 1) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo o distancia: +3 al impacto, alcance 1,5 m o 6/18 m, un objetivo. Impacto: 4 (1d6 + 1) de daño perforante."}},
        ],
    },
    {
        "slug": "sahuagin",
        "name": {"en": "Sahuagin", "es": "Sahuagin"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Lawful Evil", "es": "Legal malvado"},
        "armorClass": {"value": 12, "type": "natural armor"},
        "hitPoints": {"average": 22, "roll": "4d8+4"},
        "speed": {"walk": 30, "swim": 40},
        "abilities": {"str": 13, "dex": 11, "con": 12, "int": 12, "wis": 13, "cha": 9},
        "damageResistances": [],
        "senses": {"en": "darkvision 120 ft., passive Perception 11", "es": "visión en la oscuridad 36 m, Percepción pasiva 11"},
        "languages": {"en": "Sahuagin", "es": "Sahuagin"},
        "challengeRating": "1/2", "experiencePoints": 100,
        "traits": [
            {"name": {"en": "Blood Frenzy.", "es": "Frenesí de sangre."},
             "text": {"en": "The sahuagin has advantage on melee attack rolls against any creature that doesn't have all its HP.",
                      "es": "El sahuagin tiene ventaja en tiradas de ataque cuerpo a cuerpo contra cualquier criatura que no tenga todos sus PG."}},
            {"name": {"en": "Limited Amphibiousness.", "es": "Anfibia limitada."},
             "text": {"en": "The sahuagin can breathe air and water, but it needs to be submerged at least once every 4 hours to avoid suffocating.",
                      "es": "El sahuagin puede respirar aire y agua, pero necesita sumergirse al menos una vez cada 4 horas o se ahoga."}},
            {"name": {"en": "Shark Telepathy.", "es": "Telepatía con tiburones."},
             "text": {"en": "The sahuagin can magically command any shark within 120 ft., using a limited telepathy.",
                      "es": "El sahuagin puede ordenar mágicamente a cualquier tiburón a 36 m o menos, mediante una telepatía limitada."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The sahuagin makes two melee attacks: one with its bite and one with its claws.",
                      "es": "El sahuagin hace dos ataques cuerpo a cuerpo: uno con mordisco y otro con garras."}},
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 3 (1d4 + 1) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, un objetivo. Impacto: 3 (1d4 + 1) de daño perforante."}},
            {"name": {"en": "Claws.", "es": "Garras."},
             "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 3 (1d4 + 1) slashing damage.",
                      "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, un objetivo. Impacto: 3 (1d4 + 1) de daño cortante."}},
            {"name": {"en": "Spear.", "es": "Lanza."},
             "text": {"en": "Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6 + 1) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo o distancia: +3 al impacto, alcance 1,5 m o 6/18 m, un objetivo. Impacto: 4 (1d6 + 1) de daño perforante."}},
        ],
    },
    {
        "slug": "orog",
        "name": {"en": "Orog", "es": "Orog"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 18, "type": "plate armor"},
        "hitPoints": {"average": 60, "roll": "8d8+24"},
        "speed": {"walk": 30},
        "abilities": {"str": 18, "dex": 12, "con": 16, "int": 12, "wis": 14, "cha": 10},
        "senses": {"en": "darkvision 60 ft., passive Perception 12", "es": "visión en la oscuridad 18 m, Percepción pasiva 12"},
        "languages": {"en": "Common, Orc", "es": "Común, orco"},
        "challengeRating": "2", "experiencePoints": 450,
        "traits": [{"name": {"en": "Aggressive.", "es": "Agresivo."},
                    "text": {"en": "As a bonus action, the orog can move up to its speed toward a hostile creature it can see.",
                             "es": "Como acción adicional, el orog puede moverse hasta su velocidad hacia una criatura hostil que pueda ver."}}],
        "actions": [
            {"name": {"en": "Greatsword.", "es": "Espadón."},
             "text": {"en": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 4) slashing damage, or 11 (2d8 + 3) if used with two hands.",
                      "es": "Ataque cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 10 (2d6 + 4) de daño cortante, o 11 (2d8 + 3) a dos manos."}},
            {"name": {"en": "Javelin.", "es": "Javelina."},
             "text": {"en": "Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 30/120 ft. Hit: 7 (2d6 + 1) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo o distancia: +6 al impacto, alcance 1,5 m o 9/36 m. Impacto: 7 (2d6 + 1) de daño perforante."}},
        ],
    },
    {
        "slug": "troglodyte",
        "name": {"en": "Troglodyte", "es": "Troglodita"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 11, "type": "natural armor"},
        "hitPoints": {"average": 13, "roll": "3d8"},
        "speed": {"walk": 30},
        "abilities": {"str": 14, "dex": 10, "con": 13, "int": 6, "wis": 8, "cha": 6},
        "senses": {"en": "darkvision 60 ft., passive Perception 9", "es": "visión en la oscuridad 18 m, Percepción pasiva 9"},
        "languages": {"en": "Troglodyte", "es": "Troglodita"},
        "challengeRating": "1/2", "experiencePoints": 100,
        "traits": [
            {"name": {"en": "Chameleon Skin.", "es": "Piel de camaleón."},
             "text": {"en": "The troglodyte has advantage on Stealth checks made to hide.",
                      "es": "El troglodita tiene ventaja en pruebas de Sigilo hechas para esconderse."}},
            {"name": {"en": "Stench.", "es": "Hedor."},
             "text": {"en": "Any creature other than a troglodyte that starts its turn within 5 ft. of the troglodyte must succeed on a DC 11 CON save or be poisoned until the start of its next turn.",
                      "es": "Cualquier criatura que no sea troglodita que inicie su turno a 1,5 m o menos del troglodita debe superar CD 11 CON o estar envenenada hasta el inicio de su próximo turno."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The troglodyte makes three attacks: two with its bite and one with its claws.",
                      "es": "El troglodita hace tres ataques: dos con mordisco y uno con garras."}},
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d4 + 2) de daño perforante."}},
            {"name": {"en": "Claws.", "es": "Garras."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) slashing damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d4 + 2) de daño cortante."}},
        ],
    },
    {
        "slug": "gnoll",
        "name": {"en": "Gnoll", "es": "Gnoll"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 12, "type": "hide armor, shield"},
        "hitPoints": {"average": 22, "roll": "5d8"},
        "speed": {"walk": 30},
        "abilities": {"str": 14, "dex": 12, "con": 11, "int": 6, "wis": 9, "cha": 7},
        "senses": {"en": "darkvision 60 ft., passive Perception 9", "es": "visión en la oscuridad 18 m, Percepción pasiva 9"},
        "languages": {"en": "Gnoll", "es": "Gnoll"},
        "challengeRating": "1/2", "experiencePoints": 100,
        "traits": [{"name": {"en": "Rampage.", "es": "Desbocadura."},
                    "text": {"en": "If the gnoll reduces a creature to 0 HP with a melee attack, the gnoll can take a bonus action to move up to half its speed and make a bite attack.",
                             "es": "Si el gnoll reduce una criatura a 0 PG con un ataque cuerpo a cuerpo, puede tomar una acción adicional para moverse hasta la mitad de su velocidad y hacer un ataque de mordisco."}}],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d4 + 2) de daño perforante."}},
            {"name": {"en": "Spear.", "es": "Lanza."},
             "text": {"en": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo o distancia: +4 al impacto, alcance 1,5 m o 6/18 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante."}},
        ],
    },
    {
        "slug": "centaur",
        "name": {"en": "Centaur", "es": "Centauro"},
        "type": {"en": "Monstrosity", "es": "Monstruosidad"},
        "size": "Large", "alignment": {"en": "Neutral", "es": "Neutral"},
        "armorClass": {"value": 12, "type": "natural armor"},
        "hitPoints": {"average": 45, "roll": "6d10+12"},
        "speed": {"walk": 50},
        "abilities": {"str": 18, "dex": 14, "con": 14, "int": 9, "wis": 13, "cha": 11},
        "savingThrows": {"dex": 4},
        "skills": {"perception": 3, "survival": 3},
        "senses": {"en": "passive Perception 13", "es": "Percepción pasiva 13"},
        "languages": {"en": "Elvish, Sylvan", "es": "Élfico, silvano"},
        "challengeRating": "2", "experiencePoints": 450,
        "traits": [{"name": {"en": "Charge.", "es": "Carga."},
                    "text": {"en": "If the centaur moves at least 30 ft. straight toward a target and then hits with a hooves attack in the same turn, the target takes an extra 9 (2d8) bludgeoning damage and must succeed on a DC 13 STR save or be knocked prone.",
                             "es": "Si el centauro se mueve al menos 9 m en línea recta hacia un objetivo y luego impacta con un ataque de pezuñas en el mismo turno, el objetivo recibe 9 (2d8) adicionales de daño contundente y debe superar CD 13 FUE o caer derribado."}}],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The centaur makes two attacks: one with its hooves and one with its longbow.",
                      "es": "El centauro hace dos ataques: uno con pezuñas y otro con arco largo."}},
            {"name": {"en": "Hooves.", "es": "Pezuñas."},
             "text": {"en": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) bludgeoning damage.",
                      "es": "Ataque cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 11 (2d6 + 4) de daño contundente."}},
            {"name": {"en": "Longbow.", "es": "Arco largo."},
             "text": {"en": "Ranged Weapon Attack: +4 to hit, range 150/600 ft. Hit: 6 (1d8 + 2) piercing damage.",
                      "es": "Ataque a distancia: +4 al impacto, alcance 45/180 m. Impacto: 6 (1d8 + 2) de daño perforante."}},
        ],
    },
    {
        "slug": "kenku",
        "name": {"en": "Kenku", "es": "Kenku"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Chaotic Neutral", "es": "Caótico neutral"},
        "armorClass": {"value": 13, "type": "leather armor"},
        "hitPoints": {"average": 13, "roll": "3d8"},
        "speed": {"walk": 30},
        "abilities": {"str": 10, "dex": 13, "con": 10, "int": 10, "wis": 12, "cha": 10},
        "savingThrows": {"dex": 3},
        "skills": {"deception": 4, "stealth": 5},
        "senses": {"en": "passive Perception 11", "es": "Percepción pasiva 11"},
        "languages": {"en": "Common (understands but can't speak)", "es": "Común (entiende pero no puede hablar)"},
        "challengeRating": "1/4", "experiencePoints": 50,
        "traits": [
            {"name": {"en": "Mimicry.", "es": "Mimetismo."},
             "text": {"en": "The kenku can mimic any sounds it has heard, including voices. A creature that hears the sounds can tell they are imitations only with a successful DC 14 Investigation check.",
                      "es": "El kenku puede imitar cualquier sonido que haya escuchado, incluidas voces. Una criatura que oiga los sonidos puede distinguirlos como imitaciones con una prueba de Investigación CD 14 exitosa."}},
        ],
        "actions": [
            {"name": {"en": "Shortsword.", "es": "Espada corta."},
             "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d6 + 1) de daño perforante."}},
            {"name": {"en": "Shortbow.", "es": "Arco corto."},
             "text": {"en": "Ranged Weapon Attack: +3 to hit, range 80/320 ft. Hit: 5 (1d6 + 1) piercing damage.",
                      "es": "Ataque a distancia: +3 al impacto, alcance 24/96 m. Impacto: 5 (1d6 + 1) de daño perforante."}},
        ],
    },
    {
        "slug": "kobold",
        "name": {"en": "Kobold", "es": "Kobold"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Small", "alignment": {"en": "Lawful Evil", "es": "Legal malvado"},
        "armorClass": {"value": 12, "type": "leather armor, shield"},
        "hitPoints": {"average": 5, "roll": "2d6-2"},
        "speed": {"walk": 30},
        "abilities": {"str": 7, "dex": 15, "con": 9, "int": 8, "wis": 7, "cha": 8},
        "skills": {"stealth": 4},
        "senses": {"en": "darkvision 60 ft., passive Perception 8", "es": "visión en la oscuridad 18 m, Percepción pasiva 8"},
        "languages": {"en": "Common, Draconic", "es": "Común, dracónico"},
        "challengeRating": "1/8", "experiencePoints": 25,
        "traits": [{"name": {"en": "Pack Tactics.", "es": "Tácticas de manada."},
                    "text": {"en": "The kobold has advantage on attack rolls against a creature if at least one of the kobold's allies is within 5 ft. of the creature and the ally isn't incapacitated.",
                             "es": "El kobold tiene ventaja en tiradas de ataque contra una criatura si al menos un aliado está a 1,5 m o menos de la criatura y no está incapacitado."}}],
        "actions": [
            {"name": {"en": "Dagger.", "es": "Daga."},
             "text": {"en": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft. Hit: 4 (1d4 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo o distancia: +4 al impacto, alcance 1,5 m o 6/18 m. Impacto: 4 (1d4 + 2) de daño perforante."}},
            {"name": {"en": "Sling.", "es": "Honda."},
             "text": {"en": "Ranged Weapon Attack: +4 to hit, range 30/120 ft. Hit: 4 (1d4 + 2) bludgeoning damage.",
                      "es": "Ataque a distancia: +4 al impacto, alcance 9/36 m. Impacto: 4 (1d4 + 2) de daño contundente."}},
        ],
    },
    # === Lycanthropes ===
    {
        "slug": "wererat",
        "name": {"en": "Wererat", "es": "Hombre-rata"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Lawful Evil", "es": "Legal malvado"},
        "armorClass": {"value": 12, "type": "leather armor"},
        "hitPoints": {"average": 75, "roll": "10d8+30"},
        "speed": {"walk": 30},
        "abilities": {"str": 11, "dex": 15, "con": 12, "int": 10, "wis": 12, "cha": 11},
        "damageImmunities": ["bludgeoning, piercing, and slashing from nonmagical attacks that aren't silvered"],
        "senses": {"en": "darkvision 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, Percepción pasiva 11"},
        "languages": {"en": "Common (can't speak in rat form)", "es": "Común (no puede hablar en forma de rata)"},
        "challengeRating": "2", "experiencePoints": 450,
        "traits": [
            {"name": {"en": "Shapechanger.", "es": "Cambiaformas."},
             "text": {"en": "The wererat can use its action to polymorph into a rat-humanoid hybrid or into a giant rat, or back into its true form, which is humanoid. Its statistics, not including AC, are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies.",
                      "es": "El hombre-rata puede usar su acción para transmutarse en un híbrido rata-humanoide o en una rata gigante, o volver a su forma verdadera (humanoide). Sus estadísticas, excepto la CA, son iguales en cada forma. Cualquier equipo que lleve encima no se transforma. Vuelve a su forma verdadera si muere."}},
            {"name": {"en": "Keen Smell.", "es": "Olfato agudo."},
             "text": {"en": "The wererat has advantage on Perception checks that rely on smell.",
                      "es": "El hombre-rata tiene ventaja en pruebas de Percepción basadas en olfato."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "In humanoid form, the wererat makes two attacks, either with its shortsword or its hand crossbow.",
                      "es": "En forma humanoide, el hombre-rata hace dos ataques, con espada corta o con ballesta de mano."}},
            {"name": {"en": "Shortsword.", "es": "Espada corta."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante."}},
            {"name": {"en": "Hand Crossbow.", "es": "Ballesta de mano."},
             "text": {"en": "Ranged Weapon Attack: +4 to hit, range 30/120 ft. Hit: 5 (1d6 + 2) piercing damage.",
                      "es": "Ataque a distancia: +4 al impacto, alcance 9/36 m. Impacto: 5 (1d6 + 2) de daño perforante."}},
            {"name": {"en": "Bite (Rat or Hybrid Form Only).", "es": "Mordisco (solo forma de rata o híbrido)."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage. If the target is a humanoid, it must succeed on a DC 12 CON save or contract wererat lycanthropy.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d4 + 2) de daño perforante. Si el objetivo es humanoide, debe superar CD 12 CON o contraer licantropía de hombre-rata."}},
        ],
    },
    {
        "slug": "werewolf",
        "name": {"en": "Werewolf", "es": "Hombre-lobo"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 11, "type": "natural armor (wolf form) or no armor"},
        "hitPoints": {"average": 58, "roll": "9d8+18"},
        "speed": {"walk": 30},
        "abilities": {"str": 15, "dex": 13, "con": 14, "int": 10, "wis": 11, "cha": 10},
        "damageImmunities": ["bludgeoning, piercing, and slashing from nonmagical attacks that aren't silvered"],
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Common (can't speak in wolf form)", "es": "Común (no puede hablar en forma de lobo)"},
        "challengeRating": "3", "experiencePoints": 700,
        "traits": [
            {"name": {"en": "Shapechanger.", "es": "Cambiaformas."},
             "text": {"en": "The werewolf can use its action to polymorph into a wolf-humanoid hybrid or into a wolf, or back into its true form, which is humanoid. Its statistics, not including AC, are the same in each form. Equipment isn't transformed. Reverts to humanoid form if it dies.",
                      "es": "El hombre-lobo puede usar su acción para transmutarse en un híbrido lobo-humanoide o en un lobo, o volver a su forma verdadera (humanoide). Sus estadísticas, excepto la CA, son iguales en cada forma. Equipo no transformado. Vuelve a humanoide si muere."}},
            {"name": {"en": "Keen Hearing and Smell.", "es": "Oído y olfato agudos."},
             "text": {"en": "Advantage on Perception checks that rely on hearing or smell.",
                      "es": "Ventaja en pruebas de Percepción basadas en oído u olfato."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "In humanoid form: two attacks (one bite, one shortsword). In wolf/hybrid form: two bites.",
                      "es": "En forma humanoide: dos ataques (mordisco + espada corta). En forma de lobo/híbrido: dos mordiscos."}},
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage. Humanoid target must succeed DC 12 CON or contract werewolf lycanthropy.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 6 (1d6 + 3) de daño perforante. Si humanoide, CD 12 CON o licantropía de hombre-lobo."}},
        ],
    },
    # === Iconic creatures ===
    {
        "slug": "displacer-beast",
        "name": {"en": "Displacer Beast", "es": "Bestia desplazadora"},
        "type": {"en": "Monstrosity", "es": "Monstruosidad"},
        "size": "Large", "alignment": {"en": "Lawful Evil", "es": "Legal malvada"},
        "armorClass": {"value": 13, "type": "natural armor"},
        "hitPoints": {"average": 85, "roll": "10d10+30"},
        "speed": {"walk": 40, "fly": 40},
        "abilities": {"str": 18, "dex": 15, "con": 16, "int": 7, "wis": 12, "cha": 10},
        "senses": {"en": "darkvision 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, Percepción pasiva 11"},
        "languages": {"en": "—", "es": "—"},
        "environment": ["Underdark", "Feywild margin"],
        "challengeRating": "3", "experiencePoints": 700,
        "traits": [
            {"name": {"en": "Avoidance.", "es": "Elusión."},
             "text": {"en": "If the displacer beast is subjected to an attack, it has advantage on its next attack roll against that attacker.",
                      "es": "Si la bestia desplazadora está sujeta a un ataque, tiene ventaja en su próxima tirada de ataque contra ese atacante."}},
            {"name": {"en": "Displacement.", "es": "Desplazamiento."},
             "text": {"en": "The displacer beast projects a magical illusion that makes it appear to be standing near its actual location. Attack rolls against the beast have disadvantage unless the attacker can see through illusions.",
                      "es": "La bestia desplazadora proyecta una ilusión mágica que la hace parecer estar cerca de su ubicación real. Las tiradas de ataque contra la bestia tienen desventaja a menos que el atacante pueda ver a través de ilusiones."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The displacer beast makes two attacks: one with its bite and one with its tentacle.",
                      "es": "La bestia desplazadora hace dos ataques: uno con mordisco y otro con tentáculo."}},
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, un objetivo. Impacto: 7 (1d6 + 4) de daño perforante."}},
            {"name": {"en": "Tentacle.", "es": "Tentáculo."},
             "text": {"en": "Melee Weapon Attack: +5 to hit, reach 10 ft., one target. Hit: 5 (1d6 + 2) bludgeoning damage plus 7 (2d6) necrotic damage.",
                      "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 3 m, un objetivo. Impacto: 5 (1d6 + 2) de daño contundente + 7 (2d6) de daño necrótico."}},
        ],
    },
    {
        "slug": "rust-monster",
        "name": {"en": "Rust Monster", "es": "Monstruo del óxido"},
        "type": {"en": "Monstrosity", "es": "Monstruosidad"},
        "size": "Medium", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 14, "type": "natural armor"},
        "hitPoints": {"average": 27, "roll": "5d8+5"},
        "speed": {"walk": 40},
        "abilities": {"str": 14, "dex": 12, "con": 13, "int": 2, "wis": 13, "cha": 6},
        "savingThrows": {"dex": 3},
        "senses": {"en": "darkvision 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, Percepción pasiva 11"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1/2", "experiencePoints": 100,
        "traits": [
            {"name": {"en": "Iron Metabolism.", "es": "Metabolismo del hierro."},
             "text": {"en": "The rust monster eats metal. Its bite doesn't deal damage, but if the target is wearing nonmagical metal armor, the armor corrodes and is destroyed.",
                      "es": "El monstruo del óxido come metal. Su mordisco no causa daño, pero si el objetivo lleva armadura metálica no-mágica, la armadura se corroe y se destruye."}},
            {"name": {"en": "Rust Metal.", "es": "Oxidar metal."},
             "text": {"en": "Any nonmagical weapon made of metal that hits the rust monster corrodes and loses 2 damage die after dealing damage.",
                      "es": "Cualquier arma no-mágica de metal que impacte al monstruo del óxido se corroe y pierde 2 dados de daño después de infligir daño."}},
        ],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) bludgeoning damage. If the target is wearing nonmagical metal armor, it takes a -2 penalty to AC on its next turn.",
                      "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d8 + 1) de daño contundente. Si lleva armadura metálica no-mágica, sufre -2 a la CA en su próximo turno."}},
            {"name": {"en": "Antennae.", "es": "Antenas."},
             "text": {"en": "The rust monster can use its antennae to sense ferrous metal within 30 ft. and identify its type (weapon, armor, coin, etc.).",
                      "es": "El monstruo del óxido puede usar sus antenas para detectar metal ferroso a 9 m o menos e identificar su tipo (arma, armadura, moneda, etc.)."}},
        ],
    },
    {
        "slug": "bulette",
        "name": {"en": "Bulette", "es": "Bulette"},
        "type": {"en": "Monstrosity", "es": "Monstruosidad"},
        "size": "Large", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 17, "type": "natural armor"},
        "hitPoints": {"average": 95, "roll": "10d10+40"},
        "speed": {"walk": 40, "burrow": 40},
        "abilities": {"str": 21, "dex": 11, "con": 18, "int": 2, "wis": 13, "cha": 6},
        "savingThrows": {"str": 9, "dex": 4},
        "skills": {"perception": 5},
        "senses": {"en": "darkvision 60 ft., tremorsense 60 ft., passive Perception 15", "es": "visión en la oscuridad 18 m, sentido de vibración 18 m, Percepción pasiva 15"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "5", "experiencePoints": 1800,
        "traits": [
            {"name": {"en": "Charge.", "es": "Carga."},
             "text": {"en": "If the bulette moves at least 30 ft. straight toward a target and then hits with a bite attack in the same turn, the target takes an extra 9 (2d8) piercing damage and must succeed on a DC 14 STR save or be knocked prone. If the target is prone, the bulette can make one stomp attack against it as a bonus action.",
                      "es": "Si el bulette se mueve al menos 9 m en línea recta hacia un objetivo y luego impacta con un mordisco en el mismo turno, el objetivo recibe 9 (2d8) adicionales de daño perforante y debe superar CD 14 FUE o caer derribado. Si derribado, el bulette puede hacer un pisoteo contra él como acción adicional."}},
            {"name": {"en": "Standing Leap.", "es": "Salto en parado."},
             "text": {"en": "The bulette's long jump is up to 30 ft. and its high jump is up to 15 ft., with or without a running start.",
                      "es": "El salto largo del bulette es de hasta 9 m, y el alto de hasta 4,5 m, con o sin carrera previa."}},
        ],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +9 to hit, reach 5 ft., one target. Hit: 15 (2d8 + 7) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +9 al impacto, alcance 1,5 m, un objetivo. Impacto: 15 (2d8 + 7) de daño perforante."}},
            {"name": {"en": "Stomp.", "es": "Pisoteo."},
             "text": {"en": "Melee Weapon Attack: +9 to hit, reach 5 ft., one prone creature. Hit: 16 (2d10 + 5) bludgeoning damage.",
                      "es": "Ataque cuerpo a cuerpo: +9 al impacto, alcance 1,5 m, una criatura derribada. Impacto: 16 (2d10 + 5) de daño contundente."}},
        ],
    },
    {
        "slug": "mimic",
        "name": {"en": "Mimic", "es": "Mímico"},
        "type": {"en": "Monstrosity", "es": "Monstruosidad"},
        "size": "Medium", "alignment": {"en": "Neutral", "es": "Neutral"},
        "armorClass": {"value": 12, "type": "natural armor"},
        "hitPoints": {"average": 58, "roll": "9d8+18"},
        "speed": {"walk": 15, "climb": 15},
        "abilities": {"str": 17, "dex": 12, "con": 15, "int": 5, "wis": 13, "cha": 8},
        "savingThrows": {"str": 6},
        "skills": {"stealth": 5},
        "damageImmunities": ["acid"],
        "conditionImmunities": ["prone"],
        "senses": {"en": "darkvision 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, Percepción pasiva 11"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "2", "experiencePoints": 450,
        "traits": [
            {"name": {"en": "Adhesive (Object Form Only).", "es": "Adhesivo (solo forma de objeto)."},
             "text": {"en": "The mimic adheres to anything that touches it. A creature within 5 ft. must succeed on a DC 13 DEX save or be grappled. The mimic can have up to 4 creatures grappled at a time.",
                      "es": "El mímico se adhiere a cualquier cosa que lo toque. Una criatura a 1,5 m o menos debe superar CD 13 DES o quedar apresada. El mímico puede tener hasta 4 criaturas apresadas a la vez."}},
            {"name": {"en": "False Appearance.", "es": "Apariencia falsa."},
             "text": {"en": "The mimic can use its action to alter its form to look like an object (chest, door, furniture, etc.). A successful DC 20 Investigation check reveals its true form.",
                      "es": "El mímico puede usar su acción para alterar su forma y parecer un objeto (cofre, puerta, mueble, etc.). Una prueba de Investigación CD 20 exitosa revela su forma verdadera."}},
            {"name": {"en": "Shapechanger.", "es": "Cambiaformas."},
             "text": {"en": "The mimic can use its action to polymorph into an object or back into its true, amorphous form. Its statistics are the same in each form.",
                             "es": "El mímico puede usar su acción para transmutarse en un objeto o volver a su forma amorfa verdadera. Sus estadísticas son iguales en cada forma."}},
        ],
        "actions": [
            {"name": {"en": "Pseudopod.", "es": "Pseudópodo."},
             "text": {"en": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) bludgeoning damage. If the mimic is in object form, the target takes an extra 7 (2d6) bludgeoning damage and DC 13 STR save or grappled.",
                      "es": "Ataque cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 7 (1d8 + 3) de daño contundente. Si está en forma de objeto, el objetivo recibe 7 (2d6) adicionales de daño contundente y CD 13 FUE o apresado."}},
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage plus 4 (1d8) acid damage.",
                      "es": "Ataque cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 7 (1d8 + 3) de daño perforante + 4 (1d8) de daño de ácido."}},
        ],
    },
    {
        "slug": "doppelganger",
        "name": {"en": "Doppelganger", "es": "Doppelgänger"},
        "type": {"en": "Monstrosity", "es": "Monstruosidad"},
        "size": "Medium", "alignment": {"en": "Neutral", "es": "Neutral"},
        "armorClass": {"value": 14, "type": "natural armor"},
        "hitPoints": {"average": 52, "roll": "8d8+16"},
        "speed": {"walk": 30, "climb": 30},
        "abilities": {"str": 11, "dex": 18, "con": 14, "int": 11, "wis": 12, "cha": 14},
        "savingThrows": {"dex": 7},
        "skills": {"deception": 5, "insight": 4},
        "conditionImmunities": ["charmed"],
        "senses": {"en": "darkvision 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, Percepción pasiva 11"},
        "languages": {"en": "Common", "es": "Común"},
        "challengeRating": "4", "experiencePoints": 1100,
        "traits": [
            {"name": {"en": "Shapechanger.", "es": "Cambiaformas."},
             "text": {"en": "The doppelganger can use its action to polymorph into a Small or Medium humanoid it has seen, or back into its true form. Its statistics are the same in each form. Equipment isn't transformed. Reverts to true form if it dies.",
                      "es": "El doppelgänger puede usar su acción para transmutarse en un humanoide Pequeño o Mediano que haya visto, o volver a su forma verdadera. Sus estadísticas son iguales en cada forma. Equipo no se transforma. Vuelve a forma verdadera si muere."}},
            {"name": {"en": "Ambusher.", "es": "Emboscar."},
             "text": {"en": "The doppelganger has advantage on attack rolls against any creature it has surprised.",
                      "es": "El doppelgänger tiene ventaja en tiradas de ataque contra cualquier criatura a la que haya sorprendido."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The doppelganger makes two attacks: one with its slam and one with its read thoughts.",
                      "es": "El doppelgänger hace dos ataques: uno con embate y otro con leer pensamientos."}},
            {"name": {"en": "Slam.", "es": "Embate."},
             "text": {"en": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 4) bludgeoning damage.",
                      "es": "Ataque cuerpo a cuerpo: +7 al impacto, alcance 1,5 m, un objetivo. Impacto: 6 (1d6 + 4) de daño contundente."}},
            {"name": {"en": "Read Thoughts.", "es": "Leer pensamientos."},
             "text": {"en": "The doppelganger magically reads the surface thoughts of one creature within 60 ft. It can target any creature, even those under the effects of nondetection.",
                      "es": "El doppelgänger lee mágicamente los pensamientos superficiales de una criatura a 18 m o menos. Puede detectar cualquier criatura, incluso bajo los efectos de no-detección."}},
        ],
    },
    {
        "slug": "animated-armor",
        "name": {"en": "Animated Armor", "es": "Armadura animada"},
        "type": {"en": "Construct", "es": "Constructo"},
        "size": "Medium", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 18, "type": "natural armor"},
        "hitPoints": {"average": 33, "roll": "6d8+6"},
        "speed": {"walk": 25},
        "abilities": {"str": 14, "dex": 11, "con": 13, "int": 1, "wis": 3, "cha": 1},
        "damageImmunities": ["poison", "psychic"],
        "conditionImmunities": ["blinded", "charmed", "deafened", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned", "stunned", "unconscious"],
        "senses": {"en": "blindsight 60 ft. (blind beyond this radius), passive Perception 6", "es": "visión ciega 18 m (ciego más allá), Percepción pasiva 6"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1", "experiencePoints": 200,
        "traits": [
            {"name": {"en": "Antimagic Susceptibility.", "es": "Susceptibilidad antimagia."},
             "text": {"en": "The armor is incapacitated while in the area of an antimagic field. If targeted by the dispel magic spell, the armor is rendered inanimate for 1 minute.",
                      "es": "La armadura está incapacitada mientras esté en el área de un campo antimagia. Si es objetivo del conjuro dispersar magia, la armadura queda inanimada por 1 minuto."}},
            {"name": {"en": "False Appearance.", "es": "Apariencia falsa."},
             "text": {"en": "While the armor remains motionless, it is indistinguishable from a normal suit of armor.",
                      "es": "Mientras la armadura permanece inmóvil, es indistinguible de un traje de armadura normal."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The armor makes two slam attacks.",
                      "es": "La armadura hace dos ataques de embate."}},
            {"name": {"en": "Slam.", "es": "Embate."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) bludgeoning damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) de daño contundente."}},
        ],
    },
    {
        "slug": "flying-sword",
        "name": {"en": "Flying Sword", "es": "Espada voladora"},
        "type": {"en": "Construct", "es": "Constructo"},
        "size": "Small", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 17, "type": "natural armor"},
        "hitPoints": {"average": 17, "roll": "5d6"},
        "speed": {"walk": 0, "fly": 50},
        "abilities": {"str": 12, "dex": 15, "con": 11, "int": 1, "wis": 5, "cha": 1},
        "savingThrows": {"dex": 4},
        "damageImmunities": ["poison", "psychic"],
        "conditionImmunities": ["blinded", "charmed", "deafened", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned", "stunned", "unconscious"],
        "senses": {"en": "blindsight 60 ft. (blind beyond), passive Perception 7", "es": "visión ciega 18 m (ciego más allá), Percepción pasiva 7"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1/4", "experiencePoints": 50,
        "traits": [
            {"name": {"en": "Antimagic Susceptibility.", "es": "Susceptibilidad antimagia."},
             "text": {"en": "The sword is incapacitated while in an antimagic field. If targeted by dispel magic, the sword is rendered inanimate for 1 minute.",
                      "es": "La espada está incapacitada mientras esté en un campo antimagia. Si se le aplica dispersar magia, queda inanimada 1 minuto."}},
            {"name": {"en": "False Appearance.", "es": "Apariencia falsa."},
             "text": {"en": "While motionless, the sword is indistinguishable from a normal sword.",
                      "es": "Mientras está inmóvil, la espada es indistinguible de una espada normal."}},
        ],
        "actions": [
            {"name": {"en": "Longsword.", "es": "Espada larga."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) slashing damage, or 6 (1d10 + 1) if used with two hands.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d8 + 1) de daño cortante, o 6 (1d10 + 1) a dos manos."}},
        ],
    },
    # === Fiends / Celestials ===
    {
        "slug": "rakshasa",
        "name": {"en": "Rakshasa", "es": "Rakshasa"},
        "type": {"en": "Fiend", "es": "Infernal"},
        "size": "Medium", "alignment": {"en": "Lawful Evil", "es": "Legal malvado"},
        "armorClass": {"value": 16, "type": "natural armor"},
        "hitPoints": {"average": 110, "roll": "20d8+20"},
        "speed": {"walk": 40},
        "abilities": {"str": 13, "dex": 19, "con": 15, "int": 16, "wis": 16, "cha": 17},
        "savingThrows": {"dex": 7, "wis": 6},
        "skills": {"deception": 7, "insight": 6},
        "damageResistances": ["bludgeoning, piercing, and slashing from nonmagical attacks"],
        "damageImmunities": ["poison"],
        "conditionImmunities": ["frightened", "poisoned"],
        "senses": {"en": "darkvision 60 ft., passive Perception 13", "es": "visión en la oscuridad 18 m, Percepción pasiva 13"},
        "languages": {"en": "Common, Infernal", "es": "Común, infernal"},
        "challengeRating": "4", "experiencePoints": 1100,
        "traits": [
            {"name": {"en": "Limited Magic Immunity.", "es": "Inmunidad limitada a la magia."},
             "text": {"en": "The rakshasa can't be affected or detected by spells of 6th level or lower, unless it wishes to be. It has advantage on saving throws against all other spells and magical effects.",
                      "es": "La rakshasa no puede ser afectada ni detectada por conjuros de nivel 6 o inferior, salvo que así lo desee. Tiene ventaja en salvaciones contra todos los demás conjuros y efectos mágicos."}},
            {"name": {"en": "Innate Spellcasting.", "es": "Lanzamiento de conjuros innato."},
             "text": {"en": "The rakshasa's innate spellcasting ability is Charisma. It can innately cast detect thoughts, disguise self, and major image at will, and the following 1/day each: charm person, create food and water, tongues.",
                      "es": "La característica de lanzamiento innato de la rakshasa es Carisma. Puede lanzar a voluntad detectar pensamientos, disfrazarse e ilusión mayor, y la siguiente (1/día cada uno): encantar persona, crear comida y agua, idiomas."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The rakshasa makes two claw attacks.",
                      "es": "La rakshasa hace dos ataques de garra."}},
            {"name": {"en": "Claw.", "es": "Garra."},
             "text": {"en": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 9 (2d6 + 4) slashing damage, and the target must succeed on a DC 15 CON save or be poisoned for 1 hour.",
                      "es": "Ataque cuerpo a cuerpo: +7 al impacto, alcance 1,5 m, un objetivo. Impacto: 9 (2d6 + 4) de daño cortante, y CD 15 CON o envenenado 1 hora."}},
        ],
    },
    {
        "slug": "oni",
        "name": {"en": "Oni", "es": "Oni"},
        "type": {"en": "Giant", "es": "Gigante"},
        "size": "Large", "alignment": {"en": "Lawful Evil", "es": "Legal malvado"},
        "armorClass": {"value": 16, "type": "chain mail"},
        "hitPoints": {"average": 110, "roll": "13d10+39"},
        "speed": {"walk": 30, "fly": 30},
        "abilities": {"str": 19, "dex": 16, "con": 17, "int": 14, "wis": 16, "cha": 15},
        "savingThrows": {"dex": 6, "con": 6, "wis": 6},
        "skills": {"perception": 6, "stealth": 6},
        "damageResistances": ["bludgeoning, piercing, and slashing from nonmagical attacks"],
        "senses": {"en": "darkvision 60 ft., passive Perception 16", "es": "visión en la oscuridad 18 m, Percepción pasiva 16"},
        "languages": {"en": "Common, Giant", "es": "Común, gigante"},
        "challengeRating": "7", "experiencePoints": 2900,
        "traits": [
            {"name": {"en": "Innate Spellcasting.", "es": "Lanzamiento de conjuros innato."},
             "text": {"en": "The oni's innate spellcasting ability is Charisma. It can innately cast darkness and gust of wind at will, and the following 1/day each: cone of cold, charm person, sleep, and faithless fang.",
                      "es": "La característica de lanzamiento innato del oni es Carisma. Puede lanzar a voluntad oscuridad y ráfaga de viento, y 1/día cada uno: cono de frío, encantar persona, sueño y faithless fang."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The oni makes two attacks: one with its claws and one with its glaive.",
                      "es": "El oni hace dos ataques: uno con garras y otro con guja."}},
            {"name": {"en": "Claw.", "es": "Garra."},
             "text": {"en": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) slashing damage.",
                      "es": "Ataque cuerpo a cuerpo: +7 al impacto, alcance 1,5 m, un objetivo. Impacto: 8 (1d8 + 4) de daño cortante."}},
            {"name": {"en": "Glaive.", "es": "Guja."},
             "text": {"en": "Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 10 (1d10 + 4) slashing damage, or 15 (2d10 + 4) if used with two hands.",
                      "es": "Ataque cuerpo a cuerpo: +7 al impacto, alcance 3 m, un objetivo. Impacto: 10 (1d10 + 4) de daño cortante, o 15 (2d10 + 4) a dos manos."}},
            {"name": {"en": "Change Shape.", "es": "Cambiar de forma."},
             "text": {"en": "The oni magically polymorphs into a Small or Medium humanoid, or back into its true form. Its statistics are the same in each form. Equipment isn't transformed. Reverts to true form if it dies.",
                      "es": "El oni se transmuta mágicamente en un humanoide Pequeño o Mediano, o vuelve a su forma verdadera. Sus estadísticas son iguales en cada forma. Equipo no transformado. Vuelve a verdadera si muere."}},
        ],
    },
    # === Undead extras ===
    {
        "slug": "shadow",
        "name": {"en": "Shadow", "es": "Sombra"},
        "type": {"en": "Undead", "es": "No-muerto"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 12},
        "hitPoints": {"average": 16, "roll": "3d8+3"},
        "speed": {"walk": 40},
        "abilities": {"str": 6, "dex": 14, "con": 13, "int": 6, "wis": 10, "cha": 8},
        "savingThrows": {"dex": 4},
        "skills": {"stealth": 4},
        "damageResistances": ["acid", "cold", "fire", "lightning", "thunder"],
        "damageImmunities": ["necrotic", "poison"],
        "conditionImmunities": ["exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"],
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1/2", "experiencePoints": 100,
        "traits": [
            {"name": {"en": "Shadow Stealth.", "es": "Sigilo sombrío."},
             "text": {"en": "While in dim light or darkness, the shadow can take the Hide action as a bonus action.",
                      "es": "En penumbra u oscuridad, la sombra puede tomar la acción Esconderse como acción adicional."}},
            {"name": {"en": "Sunlight Weakness.", "es": "Debilidad a la luz solar."},
             "text": {"en": "While in sunlight, the shadow has disadvantage on attack rolls, ability checks, and saving throws.",
                      "es": "Bajo luz solar, la sombra tiene desventaja en tiradas de ataque, pruebas de característica y salvaciones."}},
        ],
        "actions": [
            {"name": {"en": "Life Drain.", "es": "Drenaje de vida."},
             "text": {"en": "Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 9 (2d6 + 2) necrotic damage, and the target's STR score is reduced by 1d4.",
                      "es": "Ataque de hechizo cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, una criatura. Impacto: 9 (2d6 + 2) de daño necrótico, y el FUE del objetivo se reduce en 1d4."}},
        ],
    },
    {
        "slug": "banshee",
        "name": {"en": "Banshee", "es": "Fantasma aullante"},
        "type": {"en": "Undead", "es": "No-muerto"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 12},
        "hitPoints": {"average": 58, "roll": "9d8+18"},
        "speed": {"walk": 0, "fly": 40},
        "abilities": {"str": 1, "dex": 14, "con": 12, "int": 12, "wis": 11, "cha": 15},
        "damageResistances": ["acid", "fire", "lightning", "thunder"],
        "damageImmunities": ["cold", "necrotic", "poison"],
        "conditionImmunities": ["charmed", "exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "stunned", "unconscious"],
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "Common + 2 others", "es": "Común + 2 más"},
        "challengeRating": "4", "experiencePoints": 1100,
        "traits": [
            {"name": {"en": "Detect Life.", "es": "Detectar vida."},
             "text": {"en": "The banshee can magically sense the presence of living creatures within 30 ft. that aren't undead or constructs.",
                      "es": "El fantasma aullante detecta mágicamente la presencia de criaturas vivas a 9 m o menos que no sean no-muertos ni constructos."}},
            {"name": {"en": "Incorporeal Movement.", "es": "Movimiento incorpóreo."},
             "text": {"en": "The banshee can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.",
                      "es": "El fantasma aullante puede moverse a través de criaturas y objetos como si fueran terreno difícil. Recibe 5 (1d10) de daño de fuerza si termina su turno dentro de un objeto."}},
            {"name": {"en": "Unusual Nature.", "es": "Naturaleza inusual."},
             "text": {"en": "The banshee doesn't require food, drink, or sleep.",
                      "es": "El fantasma aullante no necesita comida, bebida ni sueño."}},
        ],
        "actions": [
            {"name": {"en": "Corrupting Touch.", "es": "Toque corruptor."},
             "text": {"en": "Melee Spell Attack: +4 to hit, reach 5 ft., one target. Hit: 12 (3d6 + 2) necrotic damage.",
                      "es": "Ataque de hechizo cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 12 (3d6 + 2) de daño necrótico."}},
            {"name": {"en": "Wail (Recharges 5-6).", "es": "Aullido (Recarga 5-6)."},
             "text": {"en": "All creatures within 30 ft. must make a DC 13 WIS save or drop to 0 HP. On success, takes 10 (3d6) psychic damage.",
                      "es": "Todas las criaturas a 9 m o menos deben superar CD 13 SAB o caer a 0 PG. Si tienen éxito, reciben 10 (3d6) de daño psíquico."}},
        ],
    },
    # === Celestials / Constructs ===
    {
        "slug": "couatl",
        "name": {"en": "Couatl", "es": "Couatl"},
        "type": {"en": "Celestial", "es": "Celestial"},
        "size": "Medium", "alignment": {"en": "Lawful Good", "es": "Legal bueno"},
        "armorClass": {"value": 19, "type": "natural armor"},
        "hitPoints": {"average": 97, "roll": "13d8+39"},
        "speed": {"walk": 30, "fly": 90},
        "abilities": {"str": 20, "dex": 18, "con": 17, "int": 17, "wis": 20, "cha": 18},
        "savingThrows": {"con": 6, "int": 6, "wis": 9},
        "skills": {"arcana": 6, "perception": 9},
        "damageResistances": ["radiant"],
        "damageImmunities": ["poison"],
        "conditionImmunities": ["poisoned"],
        "senses": {"en": "truesight 120 ft., passive Perception 19", "es": "visión verdadera 36 m, Percepción pasiva 19"},
        "languages": {"en": "Celestial, Common, Draconic", "es": "Celestial, común, dracónico"},
        "challengeRating": "4", "experiencePoints": 1100,
        "traits": [
            {"name": {"en": "Innate Spellcasting.", "es": "Lanzamiento de conjuros innato."},
             "text": {"en": "The couatl's innate spellcasting ability is Charisma. It can innately cast the following, requiring only verbal components: detect evil and good, detect magic, and bless (at will); cure wounds (3/day), protection from poison (3/day), sanctuary (1/day), and greater restoration (1/day).",
                      "es": "La característica de lanzamiento innato del couatl es Carisma. Puede lanzar a voluntad: detectar el bien y el mal, detectar magia, y bendecir (a voluntad); curación de heridas (3/día), protección contra veneno (3/día), santuario (1/día), y restauración mayor (1/día)."},},
        ],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +8 to hit, reach 5 ft., one creature. Hit: 13 (2d8 + 4) piercing damage, and the target must succeed on a DC 13 CON save or be poisoned for 24 hours.",
                      "es": "Ataque cuerpo a cuerpo: +8 al impacto, alcance 1,5 m, una criatura. Impacto: 13 (2d8 + 4) de daño perforante, y CD 13 CON o envenenado 24 horas."}},
            {"name": {"en": "Constrict.", "es": "Constricción."},
             "text": {"en": "Melee Weapon Attack: +8 to hit, reach 10 ft., one creature. Hit: 11 (2d6 + 4) bludgeoning damage, and the target is grappled (escape DC 16 STR). Until this grapple ends, the target takes 11 (2d6 + 4) bludgeoning damage at the start of each of its turns.",
                      "es": "Ataque cuerpo a cuerpo: +8 al impacto, alcance 3 m, una criatura. Impacto: 11 (2d6 + 4) de daño contundente, y el objetivo queda apresado (escape CD 16 FUE). Hasta que termine el apresamiento, el objetivo recibe 11 (2d6 + 4) al inicio de cada uno de sus turnos."}},
        ],
    },
    {
        "slug": "pseudodragon",
        "name": {"en": "Pseudodragon", "es": "Seudodragón"},
        "type": {"en": "Dragon", "es": "Dragón"},
        "size": "Tiny", "alignment": {"en": "Neutral Good", "es": "Neutral bueno"},
        "armorClass": {"value": 13, "type": "natural armor"},
        "hitPoints": {"average": 7, "roll": "2d4+2"},
        "speed": {"walk": 15, "fly": 60},
        "abilities": {"str": 6, "dex": 15, "con": 13, "int": 10, "wis": 12, "cha": 10},
        "skills": {"perception": 3, "stealth": 4},
        "senses": {"en": "blindsight 10 ft., darkvision 60 ft., passive Perception 13", "es": "visión ciega 3 m, visión en la oscuridad 18 m, Percepción pasiva 13"},
        "languages": {"en": "Draconic", "es": "Dracónico"},
        "challengeRating": "1/2", "experiencePoints": 100,
        "traits": [
            {"name": {"en": "Keen Senses.", "es": "Sentidos agudos."},
             "text": {"en": "The pseudodragon has advantage on Perception checks.",
                      "es": "El seudodragón tiene ventaja en pruebas de Percepción."}},
            {"name": {"en": "Magic Resistance.", "es": "Resistencia a la magia."},
             "text": {"en": "The pseudodragon has advantage on saving throws against spells and other magical effects.",
                      "es": "El seudodragón tiene ventaja en salvaciones contra conjuros y otros efectos mágicos."}},
            {"name": {"en": "Limited Telepathy.", "es": "Telepatía limitada."},
             "text": {"en": "The pseudodragon can magically communicate simple ideas, emotions, and images to any creature within 60 ft. that can understand a language.",
                      "es": "El seudodragón puede comunicar mágicamente ideas, emociones e imágenes simples a cualquier criatura a 18 m o menos que entienda un idioma."}},
            {"name": {"en": "Spectral Stealth (Recharges 5-6).", "es": "Sigilo espectral (Recarga 5-6)."},
             "text": {"en": "As a bonus action, the pseudodragon and its rider can magically turn invisible together until the pseudodragon attacks or its rider dismisses the effect.",
                      "es": "Como acción adicional, el seudodragón y su jinete pueden volverse mágicamente invisibles juntos hasta que el seudodragón ataque o el jinete disuelva el efecto."}},
        ],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage, and DC 10 CON or 3 (1d6) poison damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d4 + 2) de daño perforante, y CD 10 CON o 3 (1d6) de daño de veneno."}},
            {"name": {"en": "Sting.", "es": "Aguijón."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage, and DC 10 CON or magically fall unconscious for 1 hour.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d4 + 2) de daño perforante, y CD 10 CON o queda mágicamente inconsciente 1 hora."}},
        ],
    },
    {
        "slug": "cockatrice",
        "name": {"en": "Cockatrice", "es": "Cockatrice"},
        "type": {"en": "Monstrosity", "es": "Monstruosidad"},
        "size": "Small", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 11, "type": "natural armor"},
        "hitPoints": {"average": 12, "roll": "3d6+3"},
        "speed": {"walk": 20, "fly": 40},
        "abilities": {"str": 6, "dex": 12, "con": 12, "int": 2, "wis": 13, "cha": 5},
        "senses": {"en": "darkvision 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, Percepción pasiva 11"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1/2", "experiencePoints": 100,
        "traits": [{"name": {"en": "Magic Resistance.", "es": "Resistencia a la magia."},
                    "text": {"en": "The cockatrice has advantage on saving throws against spells and other magical effects.",
                             "es": "El cockatrice tiene ventaja en salvaciones contra conjuros y otros efectos mágicos."}}],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 3 (1d4 + 1) piercing damage, and DC 11 CON or magically begin to turn to stone. Re-save at end of each turn.",
                      "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, una criatura. Impacto: 3 (1d4 + 1) de daño perforante, y CD 11 CON o comienza mágicamente a convertirse en piedra. Re-salvación al final de cada turno."}},
        ],
    },
    {
        "slug": "ankheg",
        "name": {"en": "Ankheg", "es": "Ankheg"},
        "type": {"en": "Monstrosity", "es": "Monstruosidad"},
        "size": "Large", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 14, "type": "natural armor"},
        "hitPoints": {"average": 39, "roll": "6d10+6"},
        "speed": {"walk": 30, "burrow": 30},
        "abilities": {"str": 17, "dex": 11, "con": 13, "int": 1, "wis": 13, "cha": 6},
        "senses": {"en": "darkvision 60 ft., tremorsense 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, sentido de vibración 18 m, Percepción pasiva 11"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "2", "experiencePoints": 450,
        "traits": [{"name": {"en": "Damage Transfer.", "es": "Transferencia de daño."},
                    "text": {"en": "When the ankheg takes acid damage, it deals 7 (2d6) acid damage back to the attacker (reaction).",
                             "es": "Cuando el ankheg recibe daño de ácido, inflige 7 (2d6) de daño de ácido al atacante como reacción."}}],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) slashing damage plus 3 (1d6) acid damage.",
                      "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, un objetivo. Impacto: 7 (1d6 + 4) de daño cortante + 3 (1d6) de daño de ácido."}},
            {"name": {"en": "Acid Spray (Recharges 5-6).", "es": "Espray de ácido (Recarga 5-6)."},
             "text": {"en": "The ankheg sprays acid in a 30-ft. cone. DC 13 DEX save or 21 (6d6) acid damage; success: half.",
                      "es": "El ankheg rocía ácido en un cono de 9 m. CD 13 DES o 21 (6d6) de daño de ácido; éxito: mitad."}},
        ],
    },
    {
        "slug": "chuul",
        "name": {"en": "Chuul", "es": "Chuul"},
        "type": {"en": "Aberration", "es": "Aberración"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 16, "type": "natural armor"},
        "hitPoints": {"average": 84, "roll": "11d8+33"},
        "speed": {"walk": 30, "swim": 30},
        "abilities": {"str": 19, "dex": 10, "con": 16, "int": 7, "wis": 11, "cha": 9},
        "savingThrows": {"con": 6},
        "damageImmunities": ["poison"],
        "conditionImmunities": ["poisoned"],
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "Undercommon", "es": "Infracomún"},
        "challengeRating": "4", "experiencePoints": 1100,
        "traits": [
            {"name": {"en": "Amphibious.", "es": "Anfibio."},
             "text": {"en": "The chuul can breathe air and water.",
                      "es": "El chuul puede respirar aire y agua."}},
            {"name": {"en": "Sense Magic.", "es": "Sentir magia."},
             "text": {"en": "The chuul senses magical effects within 60 ft.",
                      "es": "El chuul detecta efectos mágicos a 18 m o menos."}},
        ],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The chuul makes two pincer attacks and one tentacle attack.",
                      "es": "El chuul hace dos ataques de pinzas y un ataque de tentáculo."}},            {"name": {"en": "Pincer.", "es": "Pinza."},
             "text": {"en": "Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage. The target is grappled (escape DC 14 STR).",
                      "es": "Ataque cuerpo a cuerpo: +6 al impacto, alcance 3 m, un objetivo. Impacto: 13 (2d8 + 4) de daño contundente. El objetivo queda apresado (escape CD 14 FUE)."}},
            {"name": {"en": "Tentacle.", "es": "Tentáculo."},
             "text": {"en": "Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 11 (2d6 + 4) bludgeoning damage plus DC 14 CON save or 7 (2d6) poison damage.",
                      "es": "Ataque cuerpo a cuerpo: +6 al impacto, alcance 3 m, un objetivo. Impacto: 11 (2d6 + 4) de daño contundente + CD 14 CON o 7 (2d6) de daño de veneno."}}],
    },
] 


written_en = written_es = 0
for m in MONSTERS:
    for lang in ("en", "es"):
        doc = build_canonical(m, lang)
        out_file = ROOT / lang / f"{m['slug']}.json"
        if out_file.exists():
            print(f"  skip-existing: {m['slug']}.{lang}")
            continue
        out_file.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        if lang == "en":
            written_en += 1
        else:
            written_es += 1

print(f"Wrote {written_en} EN + {written_es} ES = {written_en + written_es} new monster JSON files.")
