#!/usr/bin/env python3
"""Add 24 iconic SRD 5.2 (2024) monsters — EN + ES.

Each monster is a single dict-of-properties with bilingual fields stored as
{"en": ..., "es": ...} sub-dicts. The build_canonical() function flattens
into the canonical MonsterDetail shape per
`backend/src/monsters/monster.types.ts`.

Schema invariant notes:
  - speed uses ONLY {walk?, fly?, swim?, climb?, burrow?} – no `hover` key
  - savingThrows is an object Partial<Record<AbilityKey, number>>, not array
  - proficiencyBonus: CR 1-4 → 2; CR 5-8 → 3; CR 9-12 → 4
"""
import json, pathlib

ROOT = pathlib.Path("data/manuals/dnd5e-2024/monsters")
for lang in ("en", "es"):
    (ROOT / lang).mkdir(parents=True, exist_ok=True)


def localize(val, lang):
    if isinstance(val, dict) and "en" in val and "es" in val and set(val.keys()) <= {"en", "es"}:
        return val[lang]
    if isinstance(val, list):
        return [localize(v, lang) for v in val]
    if isinstance(val, dict):
        return {k: localize(v, lang) for k, v in val.items()}
    return val


def prof_bonus(cr):
    cr = cr or ""
    if cr in {"1/8", "1/4", "1/2", "1", "2", "3", "4"}:
        return 2
    if cr in {"5", "6", "7", "8"}:
        return 3
    if cr in {"9", "10", "11", "12"}:
        return 4
    return 5


def build_canonical(m, lang):
    return {
        "id": m["slug"].replace("-", "_"),
        "slug": m["slug"],
        "lang": lang,
        "source": "SRD 5.2",
        "name": localize(m["name"], lang),
        "size": m["size"],
        "type": localize(m["type"], lang),
        "alignment": localize(m["alignment"], lang),
        "armorClass": m["armorClass"],
        "hitPoints": m["hitPoints"],
        "speed": m["speed"],
        "abilities": m["abilities"],
        "savingThrows": m.get("savingThrows"),
        "skills": m.get("skills"),
        "damageVulnerabilities": m.get("damageVulnerabilities", []),
        "damageResistances": m.get("damageResistances", []),
        "damageImmunities": m.get("damageImmunities", []),
        "conditionImmunities": m.get("conditionImmunities", []),
        "senses": localize(m["senses"], lang),
        "languages": localize(m["languages"], lang),
        "proficiencyBonus": prof_bonus(m.get("challengeRating")),
        "challengeRating": m.get("challengeRating"),
        "experiencePoints": m.get("experiencePoints"),
        "traits": localize(m.get("traits", []), lang),
        "actions": localize(m.get("actions", []), lang),
        "reactions": localize(m.get("reactions", []), lang),
        "legendaryActions": localize(m.get("legendaryActions", []), lang),
        "spellcasting": localize(m.get("spellcasting", []), lang),
        "environment": localize(m.get("environment", []), lang),
        "notes": localize(m.get("notes", []), lang),
    }


# -------- 24 monsters (SRD 5.2 iconic) --------
MONSTERS = [
    # === Humanoid low-CR ===
    {
        "slug": "bandit",
        "name": {"en": "Bandit", "es": "Bandido"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any non-lawful alignment", "es": "Cualquier alineamiento no legal"},
        "armorClass": {"value": 12, "type": "leather armor"},
        "hitPoints": {"average": 11, "roll": "2d8+2"},
        "speed": {"walk": 30},
        "abilities": {"str": 10, "dex": 12, "con": 12, "int": 10, "wis": 10, "cha": 10},
        "challengeRating": "1/8", "experiencePoints": 25,
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Common", "es": "Común"},
        "traits": [{"name": {"en": "Pack Tactics.", "es": "Tácticas de manada."},
                    "text": {"en": "The bandit has advantage on attack rolls against a creature if at least one of the bandit's allies is within 5 ft. of the creature and the ally isn't incapacitated.",
                             "es": "El bandido tiene ventaja en las tiradas de ataque contra una criatura si al menos uno de sus aliados está a 1,5 m o menos de la criatura y el aliado no está incapacitado."}}],
        "actions": [
            {"name": {"en": "Scimitar.", "es": "Cimitarra."},
             "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) slashing damage.",
                      "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d6 + 1) de daño cortante."}},
            {"name": {"en": "Light Crossbow.", "es": "Ballesta ligera."},
             "text": {"en": "Ranged Weapon Attack: +3 to hit, range 80/320 ft., one target. Hit: 5 (1d8 + 1) piercing damage.",
                      "es": "Ataque a distancia: +3 al impacto, alcance 24/96 m, un objetivo. Impacto: 5 (1d8 + 1) de daño perforante."}},
        ],
    },
    {
        "slug": "bandit-captain",
        "name": {"en": "Bandit Captain", "es": "Capitán bandido"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any non-lawful alignment", "es": "Cualquier alineamiento no legal"},
        "armorClass": {"value": 15, "type": "studded leather"},
        "hitPoints": {"average": 65, "roll": "10d8+20"},
        "speed": {"walk": 30},
        "abilities": {"str": 15, "dex": 16, "con": 14, "int": 14, "wis": 11, "cha": 14},
        "challengeRating": "2", "experiencePoints": 450,
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Common, Thieves' Cant", "es": "Común, jerga criminal"},
        "traits": [{"name": {"en": "Parry.", "es": "Parada."},
                    "text": {"en": "The captain adds 2 to its AC against one opportunity attack made against it as a reaction.",
                             "es": "El capitán suma 2 a su CA contra un ataque de oportunidad que le hagan como reacción."}}],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The captain makes three melee attacks: two with its scimitar and one with its dagger.",
                      "es": "El capitán realiza tres ataques cuerpo a cuerpo: dos con la cimitarra y uno con la daga."}},
            {"name": {"en": "Scimitar.", "es": "Cimitarra."},
             "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.",
                      "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, un objetivo. Impacto: 6 (1d6 + 3) de daño cortante."}},
            {"name": {"en": "Dagger.", "es": "Daga."},
             "text": {"en": "Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 20/60 ft. Hit: 5 (1d4 + 3) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo o distancia: +5 al impacto, alcance 1,5 m o 6/18 m. Impacto: 5 (1d4 + 3) de daño perforante."}},
        ],
    },
    {
        "slug": "berserker",
        "name": {"en": "Berserker", "es": "Berserker"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any chaotic alignment", "es": "Cualquier alineamiento caótico"},
        "armorClass": {"value": 13, "type": "hide armor"},
        "hitPoints": {"average": 15, "roll": "2d8+6"},
        "speed": {"walk": 30},
        "abilities": {"str": 16, "dex": 12, "con": 17, "int": 9, "wis": 11, "cha": 9},
        "challengeRating": "1", "experiencePoints": 200,
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Common", "es": "Común"},
        "traits": [{"name": {"en": "Reckless.", "es": "Imprudente."},
                    "text": {"en": "At the start of its turn, the berserker can gain advantage on all melee weapon attack rolls during that turn, but attack rolls against it have advantage until the start of its next turn.",
                             "es": "Al inicio de su turno, el berserker puede obtener ventaja en todas las tiradas de ataque cuerpo a cuerpo durante ese turno, pero las tiradas de ataque contra él tienen ventaja hasta el inicio de su próximo turno."}}],
        "actions": [{"name": {"en": "Greataxe.", "es": "Hacha grande."},
                     "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage.",
                              "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, un objetivo. Impacto: 9 (1d12 + 3) de daño cortante."}}],
    },
    {
        "slug": "commoner",
        "name": {"en": "Commoner", "es": "Plebeo"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any alignment", "es": "Cualquier alineamiento"},
        "armorClass": {"value": 10},
        "hitPoints": {"average": 4, "roll": "1d8"},
        "speed": {"walk": 30},
        "abilities": {"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10},
        "challengeRating": "0", "experiencePoints": 0,
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Common", "es": "Común"},
        "traits": [],
        "actions": [{"name": {"en": "Club.", "es": "Garrote."},
                     "text": {"en": "Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.",
                              "es": "Ataque cuerpo a cuerpo: +2 al impacto, alcance 1,5 m, un objetivo. Impacto: 2 (1d4) de daño contundente."}}],
    },
    {
        "slug": "cultist",
        "name": {"en": "Cultist", "es": "Cultista"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any non-good alignment", "es": "Cualquier alineamiento no bueno"},
        "armorClass": {"value": 12, "type": "leather armor"},
        "hitPoints": {"average": 9, "roll": "2d8"},
        "speed": {"walk": 30},
        "abilities": {"str": 11, "dex": 12, "con": 10, "int": 10, "wis": 11, "cha": 10},
        "challengeRating": "1/8", "experiencePoints": 25,
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Common + 1 other", "es": "Común + 1 más"},
        "traits": [{"name": {"en": "Dark Devotion.", "es": "Devoción oscura."},
                    "text": {"en": "The cultist has advantage on saving throws against being charmed or frightened.",
                             "es": "El cultista tiene ventaja en salvaciones contra ser hechizado o asustado."}}],
        "actions": [{"name": {"en": "Scimitar.", "es": "Cimitarra."},
                     "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 4 (1d6 + 1) slashing damage.",
                              "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, una criatura. Impacto: 4 (1d6 + 1) de daño cortante."}}],
    },
    {
        "slug": "guard",
        "name": {"en": "Guard", "es": "Guardia"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any alignment", "es": "Cualquier alineamiento"},
        "armorClass": {"value": 16, "type": "chain shirt, shield"},
        "hitPoints": {"average": 11, "roll": "2d8+2"},
        "speed": {"walk": 30},
        "abilities": {"str": 13, "dex": 12, "con": 12, "int": 10, "wis": 11, "cha": 10},
        "challengeRating": "1/8", "experiencePoints": 25,
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Common", "es": "Común"},
        "traits": [],
        "actions": [{"name": {"en": "Spear.", "es": "Lanza."},
                     "text": {"en": "Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6 + 1) piercing damage.",
                              "es": "Ataque cuerpo a cuerpo o distancia: +3 al impacto, alcance 1,5 m o 6/18 m, un objetivo. Impacto: 4 (1d6 + 1) de daño perforante."}}],
    },
    {
        "slug": "noble",
        "name": {"en": "Noble", "es": "Noble"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any alignment", "es": "Cualquier alineamiento"},
        "armorClass": {"value": 15, "type": "fine clothing"},
        "hitPoints": {"average": 9, "roll": "2d8"},
        "speed": {"walk": 30},
        "abilities": {"str": 11, "dex": 12, "con": 11, "int": 12, "wis": 14, "cha": 13},
        "challengeRating": "1/8", "experiencePoints": 25,
        "senses": {"en": "passive Perception 12", "es": "Percepción pasiva 12"},
        "languages": {"en": "Common + 1 other", "es": "Común + 1 más"},
        "traits": [],
        "actions": [{"name": {"en": "Rapier.", "es": "Estoque."},
                     "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) piercing damage.",
                              "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d8 + 1) de daño perforante."}}],
    },
    {
        "slug": "scout",
        "name": {"en": "Scout", "es": "Explorador"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any alignment", "es": "Cualquier alineamiento"},
        "armorClass": {"value": 13, "type": "leather armor"},
        "hitPoints": {"average": 16, "roll": "3d8+3"},
        "speed": {"walk": 30},
        "abilities": {"str": 11, "dex": 14, "con": 12, "int": 13, "wis": 15, "cha": 10},
        "challengeRating": "1/2", "experiencePoints": 100,
        "senses": {"en": "passive Perception 16", "es": "Percepción pasiva 16"},
        "languages": {"en": "Common, Elvish", "es": "Común, élfico"},
        "skills": {"perception": 6, "stealth": 4},
        "traits": [{"name": {"en": "Keen Hearing and Sight.", "es": "Oído y vista agudos."},
                    "text": {"en": "The scout has advantage on Perception checks that rely on hearing or sight.",
                             "es": "El explorador tiene ventaja en pruebas de Percepción basadas en oído o vista."}}],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The scout makes two attacks: one with its shortsword and one with its longbow.",
                      "es": "El explorador hace dos ataques: uno con la espada corta y otro con el arco largo."}},
            {"name": {"en": "Shortsword.", "es": "Espada corta."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante."}},
            {"name": {"en": "Longbow.", "es": "Arco largo."},
             "text": {"en": "Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8 + 2) piercing damage.",
                      "es": "Ataque a distancia: +4 al impacto, alcance 45/180 m, un objetivo. Impacto: 6 (1d8 + 2) de daño perforante."}},
        ],
    },
    {
        "slug": "spy",
        "name": {"en": "Spy", "es": "Espía"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any alignment", "es": "Cualquier alineamiento"},
        "armorClass": {"value": 12},
        "hitPoints": {"average": 27, "roll": "6d8"},
        "speed": {"walk": 30, "climb": 30},
        "abilities": {"str": 10, "dex": 15, "con": 10, "int": 13, "wis": 12, "cha": 14},
        "challengeRating": "1", "experiencePoints": 200,
        "senses": {"en": "passive Perception 11", "es": "Percepción pasiva 11"},
        "languages": {"en": "Common, Thieves' Cant + 1 other", "es": "Común, jerga criminal + 1 más"},
        "skills": {"deception": 4, "stealth": 4, "persuasion": 4},
        "traits": [{"name": {"en": "Sneak Attack (1/Turn).", "es": "Ataque furtivo (1/turno)."},
                    "text": {"en": "The spy deals an extra 1d6 damage when it hits with a weapon attack roll that has advantage, or when the target is within 5 ft. of an ally of the spy that isn't incapacitated.",
                             "es": "El espía inflige 1d6 de daño adicional cuando impacta con un ataque que tiene ventaja, o cuando el objetivo está a 1,5 m de un aliado del espía que no esté incapacitado."}}],
        "actions": [
            {"name": {"en": "Shortsword.", "es": "Espada corta."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage, plus 1d6 sneak attack damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante + 1d6 de ataque furtivo."}},
            {"name": {"en": "Hand Crossbow.", "es": "Ballesta de mano."},
             "text": {"en": "Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 5 (1d6 + 2) piercing damage, plus 1d6 sneak attack damage.",
                      "es": "Ataque a distancia: +4 al impacto, alcance 9/36 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante + 1d6 de ataque furtivo."}},
        ],
    },
    {
        "slug": "thug",
        "name": {"en": "Thug", "es": "Matón"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Any non-good alignment", "es": "Cualquier alineamiento no bueno"},
        "armorClass": {"value": 11, "type": "leather armor"},
        "hitPoints": {"average": 32, "roll": "5d10+5"},
        "speed": {"walk": 30},
        "abilities": {"str": 15, "dex": 10, "con": 14, "int": 10, "wis": 11, "cha": 9},
        "challengeRating": "1/2", "experiencePoints": 100,
        "senses": {"en": "passive Perception 10", "es": "Percepción pasiva 10"},
        "languages": {"en": "Common", "es": "Común"},
        "traits": [{"name": {"en": "Pack Tactics.", "es": "Tácticas de manada."},
                    "text": {"en": "The thug has advantage on attack rolls against a creature if at least one of the thug's allies is within 5 ft. of the creature and the ally isn't incapacitated.",
                             "es": "El matón tiene ventaja en tiradas de ataque contra una criatura si al menos un aliado está a 1,5 m o menos de la criatura y el aliado no está incapacitado."}}],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The thug makes two melee attacks.",
                      "es": "El matón hace dos ataques cuerpo a cuerpo."}},
            {"name": {"en": "Mace.", "es": "Maza."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) bludgeoning damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) de daño contundente."}},
            {"name": {"en": "Heavy Crossbow.", "es": "Ballesta pesada."},
             "text": {"en": "Ranged Weapon Attack: +2 to hit, range 100/400 ft., one target. Hit: 5 (1d10) piercing damage.",
                      "es": "Ataque a distancia: +2 al impacto, alcance 30/120 m, un objetivo. Impacto: 5 (1d10) de daño perforante."}},
        ],
    },
    # === Goblinoids ===
    {
        "slug": "hobgoblin",
        "name": {"en": "Hobgoblin", "es": "Hobgoblin"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Lawful Evil", "es": "Legal malvado"},
        "armorClass": {"value": 18, "type": "chain mail, shield"},
        "hitPoints": {"average": 11, "roll": "2d8+2"},
        "speed": {"walk": 30},
        "abilities": {"str": 13, "dex": 12, "con": 12, "int": 13, "wis": 10, "cha": 9},
        "challengeRating": "1/2", "experiencePoints": 100,
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "Common, Goblin", "es": "Común, goblin"},
        "traits": [{"name": {"en": "Martial Advantage.", "es": "Ventaja marcial."},
                    "text": {"en": "Once per turn, the hobgoblin can deal an extra 2d6 damage to one creature it hits with a weapon attack if that creature is within 5 ft. of an ally of the hobgoblin that isn't incapacitated.",
                             "es": "Una vez por turno, el hobgoblin puede infligir 2d6 de daño adicional a una criatura impactada con un ataque de arma si esa criatura está a 1,5 m de un aliado del hobgoblin que no esté incapacitado."}}],
        "actions": [
            {"name": {"en": "Longsword.", "es": "Espada larga."},
             "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) slashing damage, or 6 (1d10 + 1) if used with two hands.",
                      "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, un objetivo. Impacto: 5 (1d8 + 1) de daño cortante, o 6 (1d10 + 1) a dos manos."}},
            {"name": {"en": "Longbow.", "es": "Arco largo."},
             "text": {"en": "Ranged Weapon Attack: +3 to hit, range 150/600 ft., one target. Hit: 5 (1d8 + 1) piercing damage.",
                      "es": "Ataque a distancia: +3 al impacto, alcance 45/180 m, un objetivo. Impacto: 5 (1d8 + 1) de daño perforante."}},
        ],
    },
    {
        "slug": "bugbear",
        "name": {"en": "Bugbear", "es": "Bugbear"},
        "type": {"en": "Humanoid", "es": "Humanoide"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 16, "type": "hide armor, shield"},
        "hitPoints": {"average": 27, "roll": "5d8+5"},
        "speed": {"walk": 30},
        "abilities": {"str": 15, "dex": 14, "con": 13, "int": 8, "wis": 11, "cha": 9},
        "challengeRating": "1", "experiencePoints": 200,
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "Common, Goblin", "es": "Común, goblin"},
        "skills": {"stealth": 6},
        "traits": [
            {"name": {"en": "Brute.", "es": "Bruto."},
             "text": {"en": "A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack).",
                      "es": "Un arma cuerpo a cuerpo inflige un dado extra de su daño cuando el bugbear impacta con ella (ya incluido en el ataque)."}},
            {"name": {"en": "Sneak Attack (1/Turn).", "es": "Ataque furtivo (1/turno)."},
             "text": {"en": "The bugbear deals an extra 2d6 damage when it hits with a weapon attack roll that has advantage, or when the target is within 5 ft. of an ally of the bugbear that isn't incapacitated.",
                             "es": "El bugbear inflige 2d6 de daño adicional cuando impacta con un ataque de arma que tiene ventaja, o cuando el objetivo está a 1,5 m de un aliado del bugbear que no esté incapacitado."}},
        ],
        "actions": [
            {"name": {"en": "Morningstar.", "es": "Lucero del alba."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 11 (2d8 + 2) piercing damage, plus 2d6 sneak attack damage.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, un objetivo. Impacto: 11 (2d8 + 2) de daño perforante + 2d6 de ataque furtivo."}},
            {"name": {"en": "Javelin.", "es": "Javelina."},
             "text": {"en": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft. Hit: 9 (2d6 + 2) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo o distancia: +4 al impacto, alcance 1,5 m o 9/36 m. Impacto: 9 (2d6 + 2) de daño perforante."}},
        ],
    },
    # === Undead ===
    {
        "slug": "zombie",
        "name": {"en": "Zombie", "es": "Zombi"},
        "type": {"en": "Undead", "es": "No-muerto"},
        "size": "Medium", "alignment": {"en": "Neutral Evil", "es": "Neutral malvado"},
        "armorClass": {"value": 8},
        "hitPoints": {"average": 22, "roll": "3d8+9"},
        "speed": {"walk": 20},
        "abilities": {"str": 13, "dex": 6, "con": 16, "int": 3, "wis": 6, "cha": 5},
        "conditionImmunities": ["poisoned"],
        "senses": {"en": "darkvision 60 ft., passive Perception 8", "es": "visión en la oscuridad 18 m, Percepción pasiva 8"},
        "languages": {"en": "understands the languages it knew in life but can't speak", "es": "entiende los idiomas que conocía en vida pero no puede hablar"},
        "challengeRating": "1/4", "experiencePoints": 50,
        "traits": [{"name": {"en": "Undead Fortitude.", "es": "Fortaleza no-muerta."},
                    "text": {"en": "If damage reduces the zombie to 0 HP, it must make a CON save with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 HP instead.",
                             "es": "Si el daño reduce al zombi a 0 PG, debe hacer una salvación de CON con CD 5 + el daño recibido, salvo que el daño sea radiante o de un crítico. Si tiene éxito, el zombi baja a 1 PG en su lugar."}}],
        "actions": [{"name": {"en": "Slam.", "es": "Golpe."},
                     "text": {"en": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) bludgeoning damage.",
                              "es": "Ataque cuerpo a cuerpo: +3 al impacto, alcance 1,5 m, un objetivo. Impacto: 4 (1d6 + 1) de daño contundente."}}],
    },
    {
        "slug": "ghoul",
        "name": {"en": "Ghoul", "es": "Ghoul"},
        "type": {"en": "Undead", "es": "No-muerto"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 10},
        "hitPoints": {"average": 22, "roll": "5d8"},
        "speed": {"walk": 30},
        "abilities": {"str": 13, "dex": 15, "con": 10, "int": 7, "wis": 10, "cha": 6},
        "conditionImmunities": ["poisoned"],
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "Common", "es": "Común"},
        "challengeRating": "1", "experiencePoints": 200,
        "traits": [],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +2 to hit, reach 5 ft., one creature. Hit: 3 (1d6) piercing damage, and DC 10 CON or paralyzed for 1 minute.",
                      "es": "Ataque cuerpo a cuerpo: +2 al impacto, alcance 1,5 m, una criatura. Impacto: 3 (1d6) de daño perforante + CD 10 CON o paralizado 1 minuto."}},
            {"name": {"en": "Claws.", "es": "Garras."},
             "text": {"en": "Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 7 (2d4 + 2) slashing damage, and DC 10 CON or paralyzed for 1 minute.",
                      "es": "Ataque cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, una criatura. Impacto: 7 (2d4 + 2) de daño cortante + CD 10 CON o paralizado 1 minuto."}},
        ],
    },
    {
        "slug": "specter",
        "name": {"en": "Specter", "es": "Espectro"},
        "type": {"en": "Undead", "es": "No-muerto"},
        "size": "Medium", "alignment": {"en": "Chaotic Evil", "es": "Caótico malvado"},
        "armorClass": {"value": 12},
        "hitPoints": {"average": 22, "roll": "5d8"},
        "speed": {"walk": 0, "fly": 50},
        "abilities": {"str": 1, "dex": 14, "con": 11, "int": 10, "wis": 10, "cha": 11},
        "damageResistances": ["acid", "cold", "fire", "lightning", "thunder"],
        "conditionImmunities": ["charmed", "exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"],
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "understands the languages it knew in life", "es": "entiende los idiomas que conocía en vida"},
        "challengeRating": "1", "experiencePoints": 200,
        "traits": [{"name": {"en": "Incorporeal Movement.", "es": "Movimiento incorpóreo."},
                    "text": {"en": "The specter can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.",
                             "es": "El espectro puede moverse a través de criaturas y objetos como si fueran terreno difícil. Recibe 5 (1d10) de daño de fuerza si termina su turno dentro de un objeto."}}],
        "actions": [{"name": {"en": "Life Drain.", "es": "Drenaje de vida."},
                     "text": {"en": "Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 10 (3d6) necrotic damage, and the target must succeed on a DC 10 CON save or its HP maximum is reduced by an amount equal to the damage taken. This reduction lasts until the target finishes a long rest. If the target's HP maximum drops to 0, it dies.",
                              "es": "Ataque de hechizo cuerpo a cuerpo: +4 al impacto, alcance 1,5 m, una criatura. Impacto: 10 (3d6) de daño necrótico y el objetivo debe superar una salvación de CON CD 10 o su máximo de PG se reduce en una cantidad igual al daño. La reducción dura hasta un descanso largo. Si el máximo llega a 0, muere."}}],
    },
    {
        "slug": "wight",
        "name": {"en": "Wight", "es": "Aparecido"},
        "type": {"en": "Undead", "es": "No-muerto"},
        "size": "Medium", "alignment": {"en": "Neutral Evil", "es": "Neutral malvado"},
        "armorClass": {"value": 14, "type": "studded leather"},
        "hitPoints": {"average": 45, "roll": "6d8+18"},
        "speed": {"walk": 30},
        "abilities": {"str": 16, "dex": 14, "con": 16, "int": 11, "wis": 13, "cha": 16},
        "damageResistances": ["acid", "cold", "fire", "lightning"],
        "conditionImmunities": ["poisoned"],
        "senses": {"en": "darkvision 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, Percepción pasiva 11"},
        "languages": {"en": "Common + 1 other", "es": "Común + 1 más"},
        "challengeRating": "3", "experiencePoints": 700,
        "traits": [],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The wight makes two attacks: one with its longsword and one with its Life Drain.",
                      "es": "El aparecido hace dos ataques: uno con la espada larga y otro con Drenaje de vida."}},
            {"name": {"en": "Longsword.", "es": "Espada larga."},
             "text": {"en": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d10 + 3) slashing damage, or 9 (1d12 + 3) if used with two hands.",
                      "es": "Ataque cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 8 (1d10 + 3) de daño cortante, o 9 (1d12 + 3) a dos manos."}},
            {"name": {"en": "Life Drain.", "es": "Drenaje de vida."},
             "text": {"en": "Melee Spell Attack: +6 to hit, reach 5 ft., one creature. Hit: 12 (3d6 + 3) necrotic damage, and DC 14 CON save or max HP reduced by amount equal to damage.",
                      "es": "Ataque de hechizo cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, una criatura. Impacto: 12 (3d6 + 3) de daño necrótico + CD 14 CON o máximo de PG reducido en la cantidad de daño."}},
        ],
    },
    {
        "slug": "wraith",
        "name": {"en": "Wraith", "es": "Ánima"},
        "type": {"en": "Undead", "es": "No-muerto"},
        "size": "Medium", "alignment": {"en": "Neutral Evil", "es": "Neutral malvado"},
        "armorClass": {"value": 13},
        "hitPoints": {"average": 67, "roll": "9d8+27"},
        "speed": {"walk": 0, "fly": 60},
        "abilities": {"str": 6, "dex": 16, "con": 16, "int": 12, "wis": 14, "cha": 15},
        "damageResistances": ["acid", "cold", "fire", "lightning", "thunder"],
        "conditionImmunities": ["charmed", "exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"],
        "senses": {"en": "darkvision 60 ft., passive Perception 12", "es": "visión en la oscuridad 18 m, Percepción pasiva 12"},
        "languages": {"en": "Common + 2 others", "es": "Común + 2 más"},
        "challengeRating": "5", "experiencePoints": 1800,
        "traits": [
            {"name": {"en": "Incorporeal Movement.", "es": "Movimiento incorpóreo."},
             "text": {"en": "The wraith can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.",
                      "es": "El ánima puede moverse a través de criaturas y objetos como si fueran terreno difícil. Recibe 5 (1d10) de daño de fuerza si termina su turno dentro de un objeto."}},
            {"name": {"en": "Sunlight Sensitivity.", "es": "Sensibilidad a la luz solar."},
             "text": {"en": "While in sunlight, the wraith has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.",
                      "es": "Bajo luz solar, el ánima tiene desventaja en tiradas de ataque y en pruebas de Sabiduría (Percepción) que dependan de la vista."}},
        ],
        "actions": [
            {"name": {"en": "Life Drain.", "es": "Drenaje de vida."},
             "text": {"en": "Melee Spell Attack: +6 to hit, reach 5 ft., one creature. Hit: 21 (4d8 + 3) necrotic damage, and DC 14 CON save or max HP reduced by amount. If a humanoid dies from this attack, it rises as a wight under the wraith's control.",
                      "es": "Ataque de hechizo cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, una criatura. Impacto: 21 (4d8 + 3) de daño necrótico + CD 14 CON o máximo de PG reducido en la cantidad de daño. Si un humanoide muere por este ataque, se alza como aparecido bajo control del ánima."}},
            {"name": {"en": "Create Specter.", "es": "Crear espectro."},
             "text": {"en": "The wraith touches a humanoid that died within the past minute. The target rises as a specter under the wraith's control.",
                      "es": "El ánima toca a un humanoide que murió en el último minuto. El objetivo se alza como espectro bajo control del ánima."}},
        ],
    },
    # === Beasts ===
    {
        "slug": "brown-bear",
        "name": {"en": "Brown Bear", "es": "Oso pardo"},
        "type": {"en": "Beast", "es": "Bestia"},
        "size": "Large", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 11},
        "hitPoints": {"average": 34, "roll": "4d10+12"},
        "speed": {"walk": 40, "climb": 30},
        "abilities": {"str": 18, "dex": 10, "con": 16, "int": 2, "wis": 13, "cha": 7},
        "senses": {"en": "passive Perception 13", "es": "Percepción pasiva 13"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1", "experiencePoints": 200,
        "traits": [{"name": {"en": "Keen Smell.", "es": "Olfato agudo."},
                    "text": {"en": "The bear has advantage on Perception checks that rely on smell.",
                             "es": "El oso tiene ventaja en pruebas de Percepción basadas en olfato."}}],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The bear makes two attacks: one with its bite and one with its claws.",
                      "es": "El oso hace dos ataques: uno con mordisco y otro con garras."}},
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.",
                      "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, un objetivo. Impacto: 8 (1d8 + 4) de daño perforante."}},
            {"name": {"en": "Claws.", "es": "Garras."},
             "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.",
                      "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, un objetivo. Impacto: 11 (2d6 + 4) de daño cortante."}},
        ],
    },
    {
        "slug": "dire-wolf",
        "name": {"en": "Dire Wolf", "es": "Lobo terrible"},
        "type": {"en": "Beast", "es": "Bestia"},
        "size": "Large", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 14, "type": "natural armor"},
        "hitPoints": {"average": 37, "roll": "5d10+10"},
        "speed": {"walk": 50},
        "abilities": {"str": 15, "dex": 15, "con": 15, "int": 3, "wis": 12, "cha": 7},
        "skills": {"perception": 3, "stealth": 4},
        "senses": {"en": "passive Perception 13", "es": "Percepción pasiva 13"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1", "experiencePoints": 200,
        "traits": [
            {"name": {"en": "Keen Hearing and Smell.", "es": "Oído y olfato agudos."},
             "text": {"en": "The wolf has advantage on Perception checks that rely on hearing or smell.",
                      "es": "El lobo tiene ventaja en pruebas de Percepción de oído u olfato."}},
            {"name": {"en": "Pack Tactics.", "es": "Tácticas de manada."},
             "text": {"en": "The wolf has advantage on attack rolls against a creature if at least one of the wolf's allies is within 5 ft. of the creature and the ally isn't incapacitated.",
                      "es": "El lobo tiene ventaja en tiradas de ataque contra una criatura si al menos un aliado está a 1,5 m o menos de la criatura y el aliado no está incapacitado."}},
        ],
        "actions": [{"name": {"en": "Bite.", "es": "Mordisco."},
                     "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage. If the target is a creature, it must succeed on a DC 11 STR save or be knocked prone.",
                              "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, un objetivo. Impacto: 10 (2d6 + 3) de daño perforante. Si el objetivo es una criatura, debe superar CD 11 FUE o caer derribado."}}],
    },
    {
        "slug": "giant-spider",
        "name": {"en": "Giant Spider", "es": "Araña gigante"},
        "type": {"en": "Beast", "es": "Bestia"},
        "size": "Large", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 14, "type": "natural armor"},
        "hitPoints": {"average": 26, "roll": "4d10+4"},
        "speed": {"walk": 30, "climb": 30},
        "abilities": {"str": 14, "dex": 16, "con": 12, "int": 2, "wis": 11, "cha": 4},
        "skills": {"stealth": 7},
        "senses": {"en": "blindsight 10 ft., darkvision 60 ft., passive Perception 10", "es": "visión ciega 3 m, visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1", "experiencePoints": 200,
        "traits": [
            {"name": {"en": "Spider Climb.", "es": "Trepar como araña."},
             "text": {"en": "The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.",
                      "es": "La araña puede trepar superficies difíciles, incluido boca abajo en techos, sin necesidad de pruebas de característica."}},
            {"name": {"en": "Web Sense.", "es": "Sentido de tela."},
             "text": {"en": "While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.",
                      "es": "Mientras esté en contacto con una tela, la araña conoce la ubicación exacta de cualquier otra criatura en contacto con la misma tela."}},
            {"name": {"en": "Web Walker.", "es": "Caminante de telas."},
             "text": {"en": "The spider ignores movement restrictions caused by webbing.",
                      "es": "La araña ignora las restricciones de movimiento causadas por telas."}},
        ],
        "actions": [
            {"name": {"en": "Bite.", "es": "Mordisco."},
             "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 7 (1d8 + 3) piercing damage, and DC 11 CON save or 9 (2d8) poison damage.",
                      "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, una criatura. Impacto: 7 (1d8 + 3) de daño perforante + CD 11 CON o 9 (2d8) de daño de veneno."}},
            {"name": {"en": "Web.", "es": "Tela."},
             "text": {"en": "Ranged Weapon Attack: +5 to hit, range 30/60 ft., one creature. Hit: the target is restrained by webbing. As an action, DC 12 STR or remain restrained.",
                      "es": "Ataque a distancia: +5 al impacto, alcance 9/18 m, una criatura. Impacto: el objetivo queda apresado por la tela. Como acción, CD 12 FUE o sigue apresado."}},
        ],
    },
    {
        "slug": "swarm-of-poisonous-snakes",
        "name": {"en": "Swarm of Poisonous Snakes", "es": "Enjambre de serpientes venenosas"},
        "type": {"en": "Beast", "es": "Bestia"},
        "size": "Medium", "alignment": {"en": "Unaligned", "es": "Sin alineamiento"},
        "armorClass": {"value": 12},
        "hitPoints": {"average": 36, "roll": "12d8"},
        "speed": {"walk": 30, "swim": 30},
        "abilities": {"str": 8, "dex": 16, "con": 13, "int": 1, "wis": 10, "cha": 3},
        "damageResistances": ["bludgeoning", "piercing", "slashing"],
        "conditionImmunities": ["charmed", "frightened", "grappled", "paralyzed", "petrified", "prone", "restrained", "stunned", "unconscious"],
        "senses": {"en": "blindsight 10 ft., passive Perception 10", "es": "visión ciega 3 m, Percepción pasiva 10"},
        "languages": {"en": "—", "es": "—"},
        "challengeRating": "1/2", "experiencePoints": 100,
        "traits": [{"name": {"en": "Swarm.", "es": "Enjambre."},
                    "text": {"en": "The swarm can occupy another creature's space and vice versa. The swarm can't regain HP or be temporarily immune to damage. It can fit through a 1-inch-wide opening.",
                             "es": "El enjambre puede ocupar el espacio de otra criatura y viceversa. El enjambre no puede recuperar PG ni ser temporalmente inmune al daño. Puede pasar por aberturas de 2,5 cm."}}],
        "actions": [{"name": {"en": "Bites.", "es": "Mordiscos."},
                     "text": {"en": "Melee Weapon Attack: +5 to hit, reach 0 ft., one creature in the swarm's space. Hit: 14 (4d6) piercing damage, or 7 (2d6) piercing if the target has resistance or immunity. DC 10 CON save or 14 (4d6) poison damage.",
                              "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 0, una criatura en el espacio del enjambre. Impacto: 14 (4d6) de daño perforante, o 7 (2d6) si el objetivo tiene resistencia o inmunidad. CD 10 CON o 14 (4d6) de daño de veneno."}}],
    },
    # === Fiend / Elemental ===
    {
        "slug": "imp",
        "name": {"en": "Imp", "es": "Diablillo"},
        "type": {"en": "Fiend", "es": "Infernal"},
        "size": "Tiny", "alignment": {"en": "Lawful Evil", "es": "Legal malvado"},
        "armorClass": {"value": 13},
        "hitPoints": {"average": 10, "roll": "3d4+3"},
        "speed": {"walk": 20, "fly": 40},
        "abilities": {"str": 6, "dex": 17, "con": 13, "int": 11, "wis": 12, "cha": 13},
        "savingThrows": {"dex": 5},
        "skills": {"deception": 3, "stealth": 5},
        "damageResistances": ["cold", "fire", "lightning"],
        "conditionImmunities": ["poisoned"],
        "senses": {"en": "darkvision 60 ft., passive Perception 11", "es": "visión en la oscuridad 18 m, Percepción pasiva 11"},
        "languages": {"en": "Infernal, Common", "es": "Infernal, común"},
        "challengeRating": "1/4", "experiencePoints": 50,
        "traits": [{"name": {"en": "Shapechanger.", "es": "Cambiaformas."},
                    "text": {"en": "The imp can use its action to polymorph into a beast form that resembles a rat (speed 20 ft.) or a raven (speed 10 ft., fly 50 ft.), or back into its true form. Its statistics are the same in each form, except for the speed changes listed.",
                             "es": "El diablillo puede usar su acción para transmutarse en una forma bestial que se asemeja a una rata (velocidad 6 m) o a un cuervo (velocidad 3 m, volar 15 m), o volver a su forma verdadera. Sus estadísticas son iguales en cada forma, salvo por los cambios de velocidad indicados."}}],
        "actions": [
            {"name": {"en": "Sting.", "es": "Aguijón."},
             "text": {"en": "Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 5 (1d4 + 3) piercing damage, and DC 11 CON save or 10 (3d6) poison damage.",
                      "es": "Ataque cuerpo a cuerpo: +5 al impacto, alcance 1,5 m, una criatura. Impacto: 5 (1d4 + 3) de daño perforante + CD 11 CON o 10 (3d6) de daño de veneno."}},
            {"name": {"en": "Invisibility.", "es": "Invisibilidad."},
             "text": {"en": "The imp magically turns invisible until it attacks or its concentration ends (as if concentrating on a spell).",
                      "es": "El diablillo se vuelve mágicamente invisible hasta que ataque o termine su concentración (como si se concentrara en un conjuro)."},
             "spellcasting": {"header": "spellcasting"}},
        ],
    },
    {
        "slug": "air-elemental",
        "name": {"en": "Air Elemental", "es": "Elemental de aire"},
        "type": {"en": "Elemental", "es": "Elemental"},
        "size": "Large", "alignment": {"en": "Neutral", "es": "Neutral"},
        "armorClass": {"value": 13},
        "hitPoints": {"average": 90, "roll": "12d10+24"},
        "speed": {"fly": 90},
        "abilities": {"str": 14, "dex": 20, "con": 14, "int": 6, "wis": 10, "cha": 6},
        "damageResistances": ["lightning", "thunder"],
        "conditionImmunities": ["exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"],
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "Auran", "es": "Auran"},
        "challengeRating": "5", "experiencePoints": 1800,
        "traits": [{"name": {"en": "Air Form.", "es": "Forma aérea."},
                    "text": {"en": "The elemental can enter a creature's space and stop there. It can move through a space as narrow as 1 inch wide without squeezing.",
                             "es": "El elemental puede entrar en el espacio de una criatura y detenerse allí. Puede moverse a través de un espacio de tan solo 2,5 cm sin apretarse."}}],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The elemental makes two slam attacks.",
                      "es": "El elemental hace dos ataques de golpe."}},
            {"name": {"en": "Slam.", "es": "Golpe."},
             "text": {"en": "Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) bludgeoning damage, or 7 (1d8 + 3) bludgeoning damage if the elemental has half HP or fewer.",
                      "es": "Ataque cuerpo a cuerpo: +8 al impacto, alcance 1,5 m, un objetivo. Impacto: 14 (2d8 + 5) de daño contundente, o 7 (1d8 + 3) de daño contundente si el elemental tiene la mitad o menos de PG."}},
            {"name": {"en": "Whirlwind (Recharges 4-6).", "es": "Remolino (Recarga 4-6)."},
             "text": {"en": "Each creature in the elemental's space must make a DC 13 STR save or take 14 (4d6) bludgeoning damage and be moved up to 20 ft.",
                      "es": "Cada criatura en el espacio del elemental debe superar CD 13 FUE o recibir 14 (4d6) de daño contundente y ser movida hasta 6 m."}},
        ],
    },
    {
        "slug": "fire-elemental",
        "name": {"en": "Fire Elemental", "es": "Elemental de fuego"},
        "type": {"en": "Elemental", "es": "Elemental"},
        "size": "Large", "alignment": {"en": "Neutral", "es": "Neutral"},
        "armorClass": {"value": 13},
        "hitPoints": {"average": 102, "roll": "12d10+36"},
        "speed": {"walk": 50},
        "abilities": {"str": 10, "dex": 17, "con": 16, "int": 6, "wis": 10, "cha": 7},
        "damageImmunities": ["fire"],
        "conditionImmunities": ["exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"],
        "senses": {"en": "darkvision 60 ft., passive Perception 10", "es": "visión en la oscuridad 18 m, Percepción pasiva 10"},
        "languages": {"en": "Ignan", "es": "Ignan"},
        "challengeRating": "5", "experiencePoints": 1800,
        "traits": [{"name": {"en": "Fire Form.", "es": "Forma de fuego."},
                    "text": {"en": "The elemental can move through a space as narrow as 1 inch wide without squeezing. Any flammable object in the elemental's space is set on fire.",
                             "es": "El elemental puede moverse a través de un espacio de tan solo 2,5 cm sin apretarse. Cualquier objeto inflamable en el espacio del elemental arde."}}],
        "actions": [
            {"name": {"en": "Multiattack.", "es": "Ataque múltiple."},
             "text": {"en": "The elemental makes two touch attacks.",
                      "es": "El elemental hace dos ataques de toque."}},
            {"name": {"en": "Touch.", "es": "Toque."},
             "text": {"en": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 14 (2d10 + 3) fire damage, or 7 (2d6) fire damage if the elemental has half HP or fewer.",
                      "es": "Ataque cuerpo a cuerpo: +6 al impacto, alcance 1,5 m, un objetivo. Impacto: 14 (2d10 + 3) de daño de fuego, o 7 (2d6) de daño de fuego si el elemental tiene la mitad o menos de PG."}},
        ],
    },
]

# === Write files ===
written_en, written_es = 0, 0
for m in MONSTERS:
    for lang in ("en", "es"):
        doc = build_canonical(m, lang)
        out_file = ROOT / lang / f"{m['slug']}.json"
        out_file.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        if lang == "en":
            written_en += 1
        else:
            written_es += 1

print(f"Wrote {written_en} EN + {written_es} ES = {written_en + written_es} monster JSON files.")
