name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-ci:
    name: Backend (Lint + Unit + E2E)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck --if-present

      - name: Lint
        run: npm run lint --if-present

      - name: Unit tests
        run: npm test -- --ci --passWithNoTests

      - name: E2E tests
        run: npm run test:e2e -- --ci

      - name: Upload coverage (unit)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage
          if-no-files-found: ignore

  # Placeholder for frontend job (future)
  # frontend-ci:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'npm'
  #         cache-dependency-path: frontend/package-lock.json
  #     - name: Install deps
  #       run: npm ci
  #       working-directory: frontend
  #     - name: Build
  #       run: npm run build --if-present
  #       working-directory: frontend
